return
{
["71a16583"] = {name = "15 Puzzles for WW (World) (Ja) (WonderWitch) (Unl)"},
["c463c126"] = {name = "50 Oto Nyouryoku (World) (Ja) (WonderWitch) (Unl)"},
["abd2bd16"] = {name = "7 Days Left (World) (Ja) (WonderWitch) (Unl)"},
["425eb893"] = {name = "Anchorz Field (Japan)"},
["04366d92"] = {name = "Armored Unit (Japan)"},
["1630d75e"] = {name = "Atodashi (World) (WonderWitch) (Unl)"},
["eefb1773"] = {name = "B.A.F. (World) (Proto) (WonderWitch) (Unl)"},
["392dd813"] = {name = "Bakusou Dekotora Densetsu for WonderSwan (Japan)"},
["1e87be36"] = {name = "Ball and Block (World) (WonderWitch) (Unl)"},
["9da44185"] = {name = "BANDAI Default Splash Screen (Japan) (Program)"},
["b4790749"] = {name = "Battle Mosquito (World) (Ja) (WonderWitch) (Unl)"},
["324622c9"] = {name = "beatmania for WonderSwan (Japan)"},
["7dd96405"] = {name = "Broom (World) (WonderWitch) (Program) (Unl)"},
["b25a0635"] = {name = "Buffers Evolution (Japan)"},
["0fc80e7f"] = {name = "Buro (World) (WonderWitch) (Unl)"},
["adb27977"] = {name = "C-Man (World) (Ja) (WonderWitch) (Unl)"},
["7f3a14c0"] = {name = "Cardcaptor Sakura - Sakura to Fushigi na Clow Card (Japan)"},
["27b3cc18"] = {name = "Chaos Gear - Michibikareshi Mono (Japan)"},
["8fe6eff8"] = {name = "Chikyou o Mamore Ozon-sou (World) (Ja) (Proto) (WonderWitch) (Unl)"},
["ccaa4853"] = {name = "Chocobo no Fushigi na Dungeon for WonderSwan (Japan) (Rev 2)"},
["a607a350"] = {name = "Chocobo no Fushigi na Dungeon for WonderSwan (Japan) (Rev 1)"},
["aa53971d"] = {name = "Chocobo no Fushigi na Dungeon for WonderSwan (Japan) (Rev 3)"},
["7fff2520"] = {name = "Chou Aniki - Otoko no Tamafuda (Japan) (Rev 4)"},
["56e2c069"] = {name = "Chou Denki Card Battle - Youfu Makai (Japan) (Rev 3)"},
["4e8909d1"] = {name = "Clock Tower for WonderSwan (Japan) (Rev 1)"},
["0cb57376"] = {name = "Crazy Climber (Japan)"},
["b1caec06"] = {name = "D's Garage 21 Koubo Game - Tane o Maku Tori (Japan)"},
["12cefb60"] = {name = "Dash Straight (World) (Ja) (WonderWitch) (Unl)"},
["6b73eced"] = {name = "Datchuchu (World) (Ja) (WonderWitch) (Unl)"},
["78516e13"] = {name = "Denkou Keijiki (World) (Ja) (WonderWitch) (Unl)"},
["b62e5dd0"] = {name = "Densha de Go! (Japan) (Rev 1)"},
["af9d8f42"] = {name = "Densha de Go! 2 (Japan)"},
["f343326e"] = {name = "Dexten (World) (WonderWitch) (Unl)"},
["94ea6ffc"] = {name = "Digimon - Ver. WonderSwan (Hong Kong) (En)"},
["6e9dd148"] = {name = "Digimon Adventure - Anode Tamer (Japan) (Rev 1)"},
["fc6946f0"] = {name = "Digimon Adventure - Anode Tamer (Japan)"},
["42ad238b"] = {name = "Digimon Adventure - Cathode Tamer (Japan)"},
["6ededaf8"] = {name = "Digimon Adventure 02 - Tag Tamers (Japan) (Rev 1)"},
["56ce1bc5"] = {name = "Digimon Adventure 02 - Tag Tamers (Japan)"},
["ab59de2e"] = {name = "Digital Monster - Ver. WonderSwan (Japan) (Rev 1)"},
["b5e675ae"] = {name = "Digital Partner (Japan)"},
["89e7d950"] = {name = "Dokodemo Hamster (Japan)"},
["c3e6defe"] = {name = "Dolls (World) (Ja) (WonderWitch) (Unl)"},
["a1722e79"] = {name = "EF-Cribbage (World) (Ja) (v0.28) (Proto) (WonderWitch) (Unl)"},
["4e467626"] = {name = "Engacho! for WonderSwan (Japan)"},
["f6569cc8"] = {name = "Features (World) (v2.001) (WonderWitch) (Unl)"},
["8922dd0b"] = {name = "Fever - Sankyo Koushiki Pachinko Simulation for WonderSwan (Japan)"},
["ce2f1a1d"] = {name = "Final Lap 2000 (Japan)"},
["f246a68e"] = {name = "Fire Pro Wrestling for WonderSwan (Japan) (Rev 5)"},
["a1fb16fc"] = {name = "Fishing Freaks - Bass Rise for WonderSwan (Japan)"},
["f2e362b8"] = {name = "From TV Animation One Piece - Mezase Kaizoku Ou! (Japan)"},
["7b1cc2ab"] = {name = "Gachagacha Nyouryoku (World) (Ja) (WonderWitch) (Unl)"},
["a193458c"] = {name = "Ganso Jajamaru-kun (Japan)"},
["4aed3911"] = {name = "Glocal Hexcite (Japan)"},
["a9f11523"] = {name = "Gomoku Narabe & Reversi - Touryuumon (Japan)"},
["00137e86"] = {name = "Goraku Ou Tango! (Japan) (Rev 2)"},
["a1656bbb"] = {name = "GunPey (Japan)"},
["4b22270d"] = {name = "Hanafuda Shiyouyo (Japan)"},
["aa525c04"] = {name = "Harobots (Japan)"},
["f75ce82c"] = {name = "Harobots (Japan) (Rev 1)"},
["38ee72d7"] = {name = "Hex Calculator (World) (Ja) (WonderWitch) (Unl)"},
["ba051d69"] = {name = "Hito (World) (Ja) (WonderWitch) (Unl)"},
["5b892c30"] = {name = "Honey (World) (Ja) (v0.4) (WonderWitch) (Program) (Unl)"},
["70aa800e"] = {name = "Hunter X Hunter - Ishi o Tsugu Mono (Japan) (Rev 2)"},
["bd6fc68a"] = {name = "Hunter X Hunter - Ishi o Tsugu Mono (Japan) (Rev 1)"},
["106cbd97"] = {name = "Invader DX & Boss DX (World) (Ja) (WonderWitch) (Unl)"},
["8240ad86"] = {name = "Ishikari (World) (Ja) (WonderWitch) (Unl)"},
["4d103236"] = {name = "Kakutou Ryouri Densetsu Bistro Recipe - Wonder Battle Hen (Japan)"},
["b048e00b"] = {name = "Kana (World) (Ja) (WonderWitch) (Unl)"},
["80c6ef12"] = {name = "Kaze no Klonoa - Moonlight Museum (Japan)"},
["517f962e"] = {name = "Keiba Yosou Shien Soft - Yosou Shinkaron (Japan)"},
["0b006d79"] = {name = "Kirin Editor + Kuro Pad (World) (Ja) (WonderWitch) (Unl)"},
["acc09417"] = {name = "Kiss Communication (World) (Ja) (WonderWitch) (Unl)"},
["3b4c60c6"] = {name = "Kiss Yori... - Seaside Serenade (Japan) (Rev 2)"},
["4c48624c"] = {name = "Kosodate Quiz - Dokodemo My Angel (Japan)"},
["ecfbcb1d"] = {name = "Kyousouba Ikusei Simulation - Keiba (Japan) (Rev 1)"},
["9e0854e2"] = {name = "Langrisser Millennium WS - The Last Century (Japan) (Rev 1)"},
["cccaf8a1"] = {name = "Last Stand (Japan)"},
["d52ee0db"] = {name = "LifeGame for WonderWitch (World) (WonderWitch) (Unl)"},
["17a5dba3"] = {name = "LNPUT (World) (Ja) (WonderWitch) (Unl)"},
["21279e82"] = {name = "Lode Runner for WonderSwan (Japan)"},
["c7493525"] = {name = "Mac the Speed Shooter (World) (Proto) (WonderWitch) (Unl)"},
["62d419cd"] = {name = "Macross - True Love Song (Japan)"},
["637ada93"] = {name = "Magical Drop for WonderSwan (Japan)"},
["e7e7fd4c"] = {name = "Mahjong Touryuumon (Japan) (Rev 3)"},
["c2ed122e"] = {name = "Mahjong Touryuumon (Japan) (Rev 1)"},
["00b31fbb"] = {name = "Makaimura for WonderSwan (Japan)"},
["12fb8b28"] = {name = "Medarot Perfect Edition - Kabuto Version (Japan)"},
["2b40745d"] = {name = "Medarot Perfect Edition - Kuwagata Version (Japan)"},
["92fbf7fb"] = {name = "Meitantei Conan - Majutsushi no Chousenjou! (Japan)"},
["e226863b"] = {name = "Meitantei Conan - Nishi no Meitantei Saidai no Kiki! (Japan)"},
["a3ead689"] = {name = "Metakomi Theraphy - Nee Kiite! (Japan)"},
["c6412766"] = {name = "Migi Mawari no Randi (World) (Proto) (WonderWitch) (Unl)"},
["9baac7bb"] = {name = "Mingle Magnet (Japan) (En,Ja) (Rev 1)"},
["53b9fef8"] = {name = "Mobile Suit Gundam MSVS (Japan)"},
["80de367d"] = {name = "MobileWonderGate (Japan) (Rev 1)"},
["eb995e86"] = {name = "Moero!! Pro Yakyuu Rookies (Japan)"},
["1454110b"] = {name = "Mogura Tatake (World) (Ja) (WonderWitch) (Unl)"},
["d675c265"] = {name = "Morita Shougi for WonderSwan (Japan)"},
["ef104e2f"] = {name = "Mr. Oha no Ko Bouken - Sai Shuushou Saraba Aishi no Shooting (World) (Ja) (WonderWitch) (Unl)"},
["4ed8820c"] = {name = "Nazo Ou Pocket (Japan)"},
["cf9868da"] = {name = "Neko no Me Byua (World) (WonderWitch) (Program) (Unl)"},
["bf8d9212"] = {name = "Neon Genesis Evangelion - Shito Ikusei (Japan)"},
["b5dbcf12"] = {name = "Nice On (Japan) (Rev 1)"},
["cbd54885"] = {name = "Nigero! (World) (WonderWitch) (Unl)"},
["44b3e67c"] = {name = "Nihon Pro Mahjong Renmei Kounin - Tetsuman (Japan) (Rev 2)"},
["04531734"] = {name = "Nobunaga no Yabou for WonderSwan (Japan)"},
["22020909"] = {name = "Omiyage o Kaou! (World) (Ja) (WonderWitch) (Unl)"},
["a2a7af25"] = {name = "One Kiri (World) (Ja) (WonderWitch) (Unl)"},
["631bd97a"] = {name = "Ou-chan no Oekaki Logic (Japan)"},
["0ab76e62"] = {name = "Oyogu Kamo (World) (Proto) (WonderWitch) (Unl)"},
["ce510135"] = {name = "Panzer Battle 3 (World) (Ja) (v3.00) (WonderWitch) (Unl)"},
["8afd218b"] = {name = "Pladel (World) (Ja) (WonderWitch) (Unl)"},
["35361250"] = {name = "Pocket Fighter (Japan)"},
["cf1c007d"] = {name = "Potential Taper - Rewoke World 03 (World) (En) (WonderWitch) (Unl)"},
["90f7e6d6"] = {name = "Pro Mahjong Kiwame for WonderSwan (Japan) (Rev 1)"},
["79c048f7"] = {name = "Puchipuchi (World) (WonderWitch) (Unl)"},
["5a41a7ba"] = {name = "Puyo Puyo Tsuu (Japan)"},
["f504cd84"] = {name = "Puzzle Bobble (Japan)"},
["21398f12"] = {name = "Radius Theta (World) (WonderWitch) (Unl)"},
["8f8608ad"] = {name = "Rainbow Islands - Putty's Party (Japan)"},
["7b9a755e"] = {name = "Renda Machine (World) (Ja) (WonderWitch) (Unl)"},
["54f597a5"] = {name = "ReSiA System (World) (Ja) (v0.10) (Proto) (WonderWitch) (Unl)"},
["14adbd4b"] = {name = "Ring Infinity (Japan)"},
["3115c951"] = {name = "Ritual (World) (Ja) (Demo) (WonderWitch) (Program) (Unl)"},
["6adf0e32"] = {name = "Robot Works (Japan)"},
["be6be690"] = {name = "Robot Works (Hong Kong) (En,Ja) (Rev 1)"},
["cd206a9e"] = {name = "Rockman & Forte - Mirai Kara no Chousensha (Japan)"},
["95c903a8"] = {name = "Saint Dagrat Monogatari (World) (Ja) (WonderWitch) (Unl)"},
["e385ee88"] = {name = "Sangokushi for WonderSwan (Japan)"},
["440b2630"] = {name = "Sangokushi II for WonderSwan (Japan)"},
["ae83f873"] = {name = "SD Gundam - Emotional Jam (Japan) (Rev 3)"},
["adfc3048"] = {name = "SD Gundam - Emotional Jam (Japan) (Rev 2)"},
["e4eb3ab1"] = {name = "SD Gundam G Generation - Gather Beat (Japan)"},
["21eb4c59"] = {name = "SD Gundam Gashapon Senki - Episode 1 (Japan)"},
["2ec1e9c8"] = {name = "SD Gundam Gashapon Senki - Episode 1 (Japan) (Alt)"},
["a2aeea26"] = {name = "Senbetsu (World) (Ja) (WonderWitch) (Unl)"},
["07a3dd46"] = {name = "Senkaiden - TV Animation Senkaiden Houshin Engi Yori (Japan)"},
["301436ac"] = {name = "Sennou Millennium (Japan)"},
["1c489351"] = {name = "Shanghai Pocket (Japan)"},
["5b76f901"] = {name = "Shin Nihon Pro Wrestling - Toukon Retsuden (Japan) (Rev 1)"},
["3ad194eb"] = {name = "Shougi Touryuumon (Japan)"},
["8655269e"] = {name = "Side Pocket for WonderSwan (Japan)"},
["edbdaed6"] = {name = "Slippery Lite (World) (Proto) (WonderWitch) (Unl)"},
["352a570d"] = {name = "Slither Link (Japan)"},
["4b8e9ef6"] = {name = "Snake for WonderSwitch (World) (WonderWitch) (Unl)"},
["1263da65"] = {name = "Soccer Yarou! - Challenge the World (Japan)"},
["f016dfe1"] = {name = "Sotsugyou for WonderSwan (Japan) (Rev 1)"},
["8d83014f"] = {name = "Space Invaders (Japan)"},
["7021d54f"] = {name = "Super Robot Taisen Compact (Japan) (Rev 2)"},
["8a8c5aa8"] = {name = "Super Robot Taisen Compact (Japan)"},
["7572e478"] = {name = "Super Robot Taisen Compact (Japan) (Rev 1)"},
["782877bc"] = {name = "Super Robot Taisen Compact 2 - Dai-1-bu - Chijou Gekidou Hen (Japan)"},
["ecbb46de"] = {name = "Super Robot Taisen Compact 2 - Dai-2-bu - Uchuu Gekishin Hen (Japan) (Rev 4)"},
["0b0f8981"] = {name = "Super Robot Taisen Compact 2 - Dai-3-bu - Ginga Kessen Hen (Japan) (Rev 2)"},
["5023db90"] = {name = "Taikyoku Igo - Heisei Kiin (Japan)"},
["18597d3c"] = {name = "Taisen Othello Game (World) (Ja) (WonderWitch) (Unl)"},
["d497c07d"] = {name = "Taitoru Moji Koudo-hyo (World) (Ja) (WonderWitch) (Unl)"},
["8b74f59a"] = {name = "Tanjou Debut for WonderSwan (Japan) (Rev 1)"},
["a5643aa3"] = {name = "Tare Panda no GunPey (Japan)"},
["e7c608e5"] = {name = "Tekken Card Challenge (Japan)"},
["6fe79bb1"] = {name = "Tenori-on (Japan) (En)"},
["ef5b6b82"] = {name = "Terrors (Japan)"},
["6f304dca"] = {name = "Tetsujin 28 Gou (Japan)"},
["7da6acb9"] = {name = "Time Bokan Series - Bokan Densetsu - Buta mo Odaterya Doronboo (Japan)"},
["21530217"] = {name = "Tokei (World) (Ja) (Demo) (WonderWitch) (Unl)"},
["91117d1b"] = {name = "Tokyo Majin Gakuen - Fuju Houroku (Japan)"},
["8e1ef5c6"] = {name = "Triangle (World) (WonderWitch) (Unl)"},
["c283ec5f"] = {name = "Trump Collection - Bottom-Up Teki Trump Seikatsu (Japan) (Rev 1)"},
["64aaf392"] = {name = "Trump Collection 2 - Bottom-Up Teki Sekaiisshuu no Tabi (Japan) (Rev 1)"},
["0d5171f0"] = {name = "Turntablist - DJ Battle (Japan)"},
["86b56511"] = {name = "Umizuri ni Ikou! (Japan)"},
["812020ef"] = {name = "Uzumaki - Denshi Kaiki Hen (Japan) (Rev 4)"},
["ca3f0b00"] = {name = "Uzumaki - Noroi Simulation (Japan)"},
["8fc9e145"] = {name = "Vaitz Blade (Japan) (Rev 1)"},
["cb4c5bd1"] = {name = "Wago (World) (Ja) (WonderWitch) (Unl)"},
["1860b655"] = {name = "Wasabi Produce - Street Dancer (Japan)"},
["ac95cae2"] = {name = "Wave Q (World) (Ja) (WonderWitch) (Unl)"},
["8902b717"] = {name = "Wave R (World) (v1.1) (WonderWitch) (Unl)"},
["06f6914e"] = {name = "Wave R (World) (v1.0) (WonderWitch) (WWGP2003) (Unl)"},
["23bc0309"] = {name = "Wonder Stadium (Japan)"},
["e252919d"] = {name = "Wonder Stadium '99 (Japan)"},
["2ab9852d"] = {name = "WonderSwan Handy Sonar (Japan) (Rev 1)"},
["d4188811"] = {name = "WonderSwan Handy Sonar (Japan) (Rev 2)"},
["dc60f640"] = {name = "WonderWitch (Japan) (FreyaOS 1.0.0) (Program)"},
["8e5e9633"] = {name = "WonderWitch (Japan) (FreyaOS 1.2.0) (Program)"},
["45ba7287"] = {name = "WonderWitch (Japan) (FreyaOS 1.1.5) (Program)"},
["71aa2e39"] = {name = "WonderWitch (Japan) (FreyaOS 1.0.2) (Program)"},
["f71ef60c"] = {name = "WonderWitch (Japan) (FreyaOS 1.0.3) (Program)"},
["f8bdf7ab"] = {name = "WonderWitch (Japan) (FreyaOS 1.1.1) (Program)"},
["05c0166e"] = {name = "WonderWitch (Japan) (FreyaOS 1.1.2) (Program)"},
["9303fa7e"] = {name = "WonderWitch (Japan) (FreyaOS 1.1.3) (Program)"},
["e8d001b8"] = {name = "WonderWitch (Japan) (FreyaOS 1.1.4) (Program)"},
["6480bf70"] = {name = "WonderWitch (Japan) (FreyaOS 1.1.6b1) (Program)"},
["72db30fd"] = {name = "WonderWitch EP-NET (World) (Ja) (WonderWitch) (Program) (Unl)"},
["fb7a1439"] = {name = "WWTerm (World) (WonderWitch) (Program) (Unl)"},
["c724ab72"] = {name = "Yoke Bin (World) (Demo) (WonderWitch) (Unl)"},
["5960ccff"] = {name = "Ze Sound Player + Sample Music (World) (WonderWitch) (Program) (Unl)"},
}