return
{
["f6fb48fb"] = {name = "A.P.B. (USA, Europe)"},
["540e9bb7"] = {name = "Alien vs Predator (USA) (Proto) (1993-12-17)"},
["0483cd2a"] = {name = "Awesome Golf (USA, Europe)"},
["3943c116"] = {name = "Baseball Heroes (USA, Europe)"},
["4161bb4a"] = {name = "Basketbrawl (USA, Europe)"},
["277f82c2"] = {name = "Batman Returns (USA, Europe)"},
["779faece"] = {name = "Battle Wheels (USA, Europe)"},
["30fee726"] = {name = "Battlezone 2000 (USA, Europe)"},
["143a313e"] = {name = "Bill & Ted's Excellent Adventure (USA, Europe)"},
["3cd75df3"] = {name = "Block Out (USA, Europe)"},
["bfe36525"] = {name = "Blue Lightning (World) (Demo)"},
["daf587b1"] = {name = "Blue Lightning (World)"},
["333daece"] = {name = "Bubble Trouble (USA, Europe)"},
["f8158766"] = {name = "Cabal (USA) (Demo)"},
["a08f0b59"] = {name = "California Games (World)"},
["97501709"] = {name = "Centipede (USA) (Proto)"},
["19c5a7a5"] = {name = "Checkered Flag (USA, Europe)"},
["6a5f53ed"] = {name = "Chip's Challenge (World)"},
["b02821fa"] = {name = "Conquest of Zow (World) (Demo) (Unl)"},
["aec474c8"] = {name = "Crystal Mines II (USA, Europe)"},
["99729395"] = {name = "Daemon's Gate (USA) (Proto 1)"},
["ef529ed4"] = {name = "Daemon's Gate (USA) (Proto 2)"},
["b9ac1fe5"] = {name = "Desert Strike - Return to the Gulf (USA, Europe)"},
["50386cfa"] = {name = "Dinolympics (USA, Europe)"},
["d565fbb7"] = {name = "Dirty Larry - Renegade Cop (USA, Europe)"},
["fbfc0f05"] = {name = "Double Dragon (USA, Europe)"},
["33bb74c7"] = {name = "Dracula - The Undead (USA, Europe)"},
["bd97116b"] = {name = "Electrocop (World)"},
["f83397f9"] = {name = "European Soccer Challenge (USA, Europe)"},
["6bceaa9c"] = {name = "Eye of the Beholder (USA) (Proto 1)"},
["f1b307cb"] = {name = "Eye of the Beholder (World) (Unl)"},
["9034ee27"] = {name = "Fat Bobby (USA, Europe)"},
["7e4b5945"] = {name = "Fidelity Ultimate Chess Challenge, The (USA, Europe)"},
["68b0a428"] = {name = "Friendly (World) (Demo) (Unl)"},
["ff9e0126"] = {name = "Full Court Press (USA) (Proto)"},
["494cc568"] = {name = "Gates of Zendocon (World)"},
["7f0ec7ad"] = {name = "Gauntlet - The Third Encounter (World)"},
["dcd723e3"] = {name = "Gauntlet - The Third Encounter (World) (Beta) (1990-06-04)"},
["bd4bf2b0"] = {name = "Geoduel (USA) (Demo)"},
["d20a85fc"] = {name = "Gordo 106 (USA, Europe)"},
["8f0e72c6"] = {name = "Guardians, The - Storm Over Doria (USA) (Proto 2)"},
["0e335aa8"] = {name = "Guardians, The - Storm Over Doria (USA) (Proto 1)"},
["6df63834"] = {name = "Hard Drivin' (USA, Europe)"},
["e8b45707"] = {name = "Hockey (USA, Europe)"},
["e3041c6c"] = {name = "Hydra (USA, Europe)"},
["5cf8bbf0"] = {name = "Ishido - The Way of Stones (USA, Europe)"},
["2455b6cf"] = {name = "Jimmy Connors' Tennis (USA, Europe)"},
["5dba792a"] = {name = "Joust (USA, Europe)"},
["a53649f1"] = {name = "Klax (World)"},
["4d5d94f4"] = {name = "Klax (World) (Beta)"},
["bed5ba2b"] = {name = "Krazy Ace - Miniature Golf (USA, Europe)"},
["cd1bd405"] = {name = "Kung Food (USA, Europe)"},
["39b9b8cc"] = {name = "Lemmings (USA, Europe)"},
["b1c25ef1"] = {name = "Loopz (USA) (v0.06) (Proto) (1992-11-05)"},
["d2b07d4d"] = {name = "Loopz (USA) (v0.04) (Proto) (1992-09-16)"},
["1091a268"] = {name = "Lynx Casino (USA, Europe)"},
["28ada019"] = {name = "Lynx II Production Test Program (USA)"},
["aba6da3d"] = {name = "Malibu Bikini Volleyball (USA, Europe)"},
["4329084a"] = {name = "Malibu Bikini Volleyball (USA, Europe) (Beta) (1993-05-11)"},
["c3fa0d4d"] = {name = "Marlboro Go! (Europe) (Proto 2)"},
["b17a36ad"] = {name = "Marlboro Go! (Europe) (Proto 1)"},
["90c28f57"] = {name = "Mines 2 (World) (Demo) (Unl)"},
["7de3783a"] = {name = "Ms. Pac-Man (World)"},
["006fd398"] = {name = "NFL Football (USA, Europe)"},
["22d47d51"] = {name = "Ninja Gaiden (USA, Europe)"},
["f3e3f811"] = {name = "Ninja Gaiden III - The Ancient Ship of Doom (USA, Europe)"},
["f428008d"] = {name = "Ninja Nerd (USA) (Demo)"},
["aa50dd22"] = {name = "Pac-Land (USA, Europe)"},
["4cdfbd57"] = {name = "Paperboy (World)"},
["14d38ca7"] = {name = "Pinball Jam (USA, Europe)"},
["2393135f"] = {name = "Pit-Fighter (USA, Europe)"},
["e7a5a4d0"] = {name = "Pit-Fighter (USA, Europe) (Beta) (1992-10-13)"},
["c45bcd62"] = {name = "Poker (Europe) (Fr) (Proto)"},
["5d1abfe7"] = {name = "Pounce! (USA) (Proto)"},
["99c42034"] = {name = "Power Factor (USA, Europe)"},
["f6f43c87"] = {name = "Puzzler 2000 (World) (Proto) (Unl)"},
["b9881423"] = {name = "QIX (USA, Europe)"},
["bcd10c3a"] = {name = "Raiden (USA) (Beta)"},
["74ec2b2b"] = {name = "RAM cart (USA) (Proto) (Program)"},
["b10b7c8e"] = {name = "Rampage (World)"},
["139f301d"] = {name = "Rampart (USA, Europe)"},
["69959a3b"] = {name = "Road Riot 4WD (USA) (Proto 4)"},
["82555eeb"] = {name = "Road Riot 4WD (USA) (Proto 3)"},
["eccea0d5"] = {name = "Road Riot 4WD (USA) (Proto 2)"},
["bfecefc3"] = {name = "Road Riot 4WD (USA) (Proto 1)"},
["6867e80c"] = {name = "RoadBlasters (World)"},
["d1dff2b2"] = {name = "Robo-Squash (World)"},
["7a6049b5"] = {name = "Robotron 2084 (USA, Europe)"},
["467f8fd9"] = {name = "Rolling Thunder (USA) (Proto)"},
["67e5bdba"] = {name = "Rygar (World)"},
["8595c40b"] = {name = "S.T.U.N. Runner (USA, Europe)"},
["be166f3b"] = {name = "Scrapyard Dog (USA, Europe)"},
["eb78baa3"] = {name = "Shadow of the Beast (USA, Europe)"},
["192bcd04"] = {name = "Shanghai (World)"},
["59510cb3"] = {name = "Spacewar (USA) (Demo)"},
["5b2308ed"] = {name = "Steel Talons (USA, Europe)"},
["2da7e2a8"] = {name = "Super Asteroids, Missile Command (USA, Europe)"},
["690caeb0"] = {name = "Super Off-Road (USA, Europe)"},
["dfa61571"] = {name = "Super Skweek (USA, Europe)"},
["13657705"] = {name = "Switchblade II (USA, Europe)"},
["ae267e29"] = {name = "Todd's Adventures in Slime World (World)"},
["156a4a4c"] = {name = "Toki (USA, Europe)"},
["0590a9e3"] = {name = "Tournament Cyberball (USA, Europe)"},
["a4b924d6"] = {name = "Turbo Sub (USA, Europe)"},
["8d56828b"] = {name = "Viking Child (USA, Europe)"},
["6e084b3a"] = {name = "Vindicators (USA) (Proto)"},
["b946ba49"] = {name = "Warbirds (USA, Europe)"},
["c5ebd679"] = {name = "Wolfman (USA) (Demo) (Kiosk)"},
["91233794"] = {name = "World Class Soccer (USA, Europe)"},
["9bed736d"] = {name = "Xenophobe (World)"},
["89e2a595"] = {name = "Xybots (USA, Europe)"},
["4ea845da"] = {name = "Zaku (World) (Unl)"},
["b3747c71"] = {name = "Zaku (World) (Beta) (Unl)"},
["cb27199d"] = {name = "Zarlor Mercenary (World)"},
}