return
{
["c99e5601"] = {name = "1942 (Japan)"},
["c956e1df"] = {name = "A Ressha de Ikou MSX (Japan)"},
["d2ee4051"] = {name = "AcroJet (Japan)"},
["76545096"] = {name = "Akumajo Dracula (Japan) (Wii U Virtual Console)"},
["c29edd84"] = {name = "Aleste (Japan)"},
["225705cc"] = {name = "Alges no Yoku (Japan)"},
["bcf03d8b"] = {name = "American Soccer (Japan)"},
["075ab646"] = {name = "Aoki Ookami to Shiroki Mejika - Genchou Hishi (Japan)"},
["3b5b3fd8"] = {name = "Aoki Ookami to Shiroki Mejika - Genghis Khan (Japan)"},
["614554c4"] = {name = "Arctic - Active Rail Playing (Japan) (Alt)"},
["ae3167ee"] = {name = "Arctic - Active Rail Playing (Japan)"},
["00d36af6"] = {name = "Arkanoid II - Revenge of Doh (Japan)"},
["3cb34efb"] = {name = "AshGuine - Densetsu no Seisenshi (Japan)"},
["47a82d74"] = {name = "AshGuine Story II - Kokuu no Gajou (Japan)"},
["353382ce"] = {name = "AshGuine Story III - Fukushuu no Honoo (Japan)"},
["8b73f133"] = {name = "Bubble Bobble (Japan) (Alt)"},
["6524d9fc"] = {name = "Bubble Bobble (Japan)"},
["2ffb49c3"] = {name = "Cheese 2 (Japan) (Program)"},
["5f354e65"] = {name = "Cockpit, The (Japan)"},
["4e82660d"] = {name = "Contra (Japan) (Wii U Virtual Console)"},
["8528a795"] = {name = "Crimson (Japan)"},
["ec7a8012"] = {name = "Daikoukai Jidai (Japan)"},
["43f14f1f"] = {name = "Daisenryaku (Japan)"},
["6fb05f43"] = {name = "Darwin 4078 (Japan) (Alt 2)"},
["7098faf0"] = {name = "Darwin 4078 (Japan)"},
["ce86a52f"] = {name = "Darwin 4078 (Japan) (Alt)"},
["3615e623"] = {name = "Deep Forest (Japan) (Alt)"},
["f221b845"] = {name = "Deep Forest (Japan)"},
["5acbd591"] = {name = "Dires - Giger Loop (Japan)"},
["e1148738"] = {name = "Double Vision (Japan)"},
["49252882"] = {name = "Dragon Buster (Japan)"},
["7729e7a9"] = {name = "Dragon Quest (Japan)"},
["e012ee7a"] = {name = "Dragon Quest II (Japan) (Alt)"},
["0bf0c3f5"] = {name = "Dragon Quest II (Japan)"},
["98095852"] = {name = "Dragon Slayer IV - Drasle Family (Japan)"},
["53163cbc"] = {name = "Dragon Slayer IV - Drasle Family (Japan) (Alt)"},
["17f9ee7f"] = {name = "Dragon Slayer Jr. - Romancia (Japan)"},
["94982598"] = {name = "Druid (Japan)"},
["c3242b0a"] = {name = "Druid (Japan) (Alt)"},
["9935e9bd"] = {name = "Dynamite Bowl (Japan)"},
["a4996aaa"] = {name = "Dynamite Bowl (Japan) (Alt)"},
["14913432"] = {name = "Eidolon, The (Europe)"},
["a8e9ac9b"] = {name = "Elthlead (Japan)"},
["c7521809"] = {name = "Empereur, L' (Japan)"},
["413d4700"] = {name = "Europe Sensen (Japan)"},
["53cce88d"] = {name = "F-15 Strike Eagle (Japan)"},
["0e03847b"] = {name = "Famicle Parodic (Japan)"},
["7c867d98"] = {name = "Family Billiards (Japan)"},
["7030f2ab"] = {name = "Family Boxing - MSX Title Match (Japan)"},
["3459ce01"] = {name = "Fantasy Zone II - The Tears of Opa-Opa (Japan) (Alt)"},
["1bdfaeeb"] = {name = "Fantasy Zone II - The Tears of Opa-Opa (Japan)"},
["fe797d88"] = {name = "Final Mystery Murder Club - Satsujin Club (Japan)"},
["cdcdc6c0"] = {name = "Fire Ball (Japan)"},
["9f152e9b"] = {name = "Fleet Commander II - Koukon no Kaiiki (Japan)"},
["fbdafe4e"] = {name = "Gakuen Monogatari - High School Story (Japan)"},
["eb67d4d6"] = {name = "Gambler Jiko Chuushinha 2 - Jishou! Kyougou Janshi Hen (Japan)"},
["40e53ea3"] = {name = "Ganbare Goemon! - Karakuri Douchuu (Japan) (Wii U Virtual Console)"},
["33c37313"] = {name = "Garakuta (Japan)"},
["2fb0ed30"] = {name = "Garyuu Ou (Japan)"},
["40d009fe"] = {name = "Garyuu Ou (Japan) (Alt)"},
["bc1b1ace"] = {name = "Gekitotsu Pennant Race - Pro Yakyuu, The (Japan) (Alt 3)"},
["b0a7800f"] = {name = "Gekitotsu Pennant Race - Pro Yakyuu, The (Japan) (Alt)"},
["0ad36e2b"] = {name = "Gekitotsu Pennant Race - Pro Yakyuu, The (Japan) (Alt 2)"},
["c08faf0e"] = {name = "Gekitotsu Pennant Race - Pro Yakyuu, The (Japan)"},
["e92fc432"] = {name = "Gekitotsu Pennant Race 2 (Japan) (English Menu)"},
["c44c6330"] = {name = "Gekitotsu Pennant Race 2 (Japan)"},
["28094960"] = {name = "Girly Block (Japan)"},
["8df56d42"] = {name = "Hacker (Japan)"},
["e0e72736"] = {name = "Hai no Majutsushi (Japan)"},
["ff05fbbf"] = {name = "Hal Note (Japan)"},
["c6f74489"] = {name = "Han Seimei Senki Andorogynus (Japan)"},
["eaf2bfcd"] = {name = "Han Seimei Senki Andorogynus (Japan) (Alt)"},
["1d7040af"] = {name = "Hard Ball (Japan)"},
["95f2eb6d"] = {name = "Heroes of the Lance (Japan)"},
["17baf3ed"] = {name = "Higemaru Makai Shima - Nanatsu no Shima Daibouken (Japan)"},
["1123545c"] = {name = "High School! Kimengumi (Japan)"},
["3ab5ae57"] = {name = "Hinotori - Houou Hen (Japan)"},
["d95116b0"] = {name = "Hinotori - Houou Hen (Japan) (Alt)"},
["5928f406"] = {name = "Hinotori - Houou Hen (Japan) (Alt 2)"},
["f35df283"] = {name = "Hole in One Special (Japan)"},
["4708bdd1"] = {name = "Hole in One Special (Japan) (Alt)"},
["00db86c8"] = {name = "Hydlide 3 - The Space Memories (Japan)"},
["935f1bde"] = {name = "Ide Yousuke Meijin no Jissen Mahjong (Japan)"},
["a9a66075"] = {name = "Ikari (Japan)"},
["93999a38"] = {name = "Ikari (Japan) (Alt)"},
["f5174422"] = {name = "Inemuriryuu Asada Tetsuya no A-kyuu Mahjong (Japan)"},
["881b3849"] = {name = "Inindou - Datou Nobunaga (Japan)"},
["8bc34dca"] = {name = "Ishin no Arashi (Japan)"},
["00b8e82e"] = {name = "Jansei (Japan)"},
["2c2924ed"] = {name = "Jansei (Japan) (Alt)"},
["459478cb"] = {name = "Japanese MSX-Write II (Japan) (Program)"},
["053aa66e"] = {name = "Kempelen Chess (Japan)"},
["5c859406"] = {name = "Kiki Kaikai (Japan)"},
["23b78a2d"] = {name = "King Kong 2 - Yomigaeru Densetsu (Japan)"},
["167a53da"] = {name = "Kisei (Japan)"},
["0767af40"] = {name = "Kitahei (Japan)"},
["fb348de6"] = {name = "Koronis Rift (Europe)"},
["9926f43c"] = {name = "Labyrinth (Japan)"},
["a295e608"] = {name = "Labyrinth (Japan) (Alt)"},
["5a090675"] = {name = "Lupin Sansei - Babylon no Ougon Densetsu (Japan) (Alt)"},
["bfe150c4"] = {name = "Lupin Sansei - Babylon no Ougon Densetsu (Japan)"},
["c4096e6b"] = {name = "Lupin Sansei - Cagliostro no Shiro (Japan)"},
["f12bec91"] = {name = "Lupin Sansei - Cagliostro no Shiro (Japan) (Alt)"},
["dfc2a720"] = {name = "Mad Rider (Japan) (Alt)"},
["f87bd172"] = {name = "Mad Rider (Japan)"},
["94191aae"] = {name = "Maison Ikkoku - Kanketsu Hen - Sayonara, Soshite... (Japan)"},
["f4d127c0"] = {name = "Maison Ikkoku - Omoide no Photograph (Japan)"},
["f7a9591d"] = {name = "Malaya no Hibou (Japan)"},
["fafe1303"] = {name = "Metal Gear (Japan)"},
["e85c5731"] = {name = "Metal Gear (Europe)"},
["dcee5080"] = {name = "Metal Gear 2 - Solid Snake (Japan) (Demo)"},
["18b1f34b"] = {name = "Metal Gear 2 - Solid Snake (Japan)"},
["70aa93cf"] = {name = "Mirai (Japan)"},
["3f69a464"] = {name = "Mississippi Satsujinjiken (Japan)"},
["68745c64"] = {name = "Moero!! Nettou Yakyuu '88 (Japan)"},
["ebccb796"] = {name = "Monmon Kaibutsu (Japan)"},
["fda1977a"] = {name = "Nekketsu Juudou (Japan) (Alt)"},
["758c6087"] = {name = "Nekketsu Juudou (Japan)"},
["f56a00e6"] = {name = "Ninja-kun - Asura no Shou (Japan)"},
["0ff8e2c7"] = {name = "Nobunaga no Yabou - Bushou Fuuun Roku (Japan)"},
["69c11d81"] = {name = "Nobunaga no Yabou - Sengoku Gunyuuden (Japan)"},
["653f1c73"] = {name = "Nobunaga no Yabou - Zenkoku Ban (Japan)"},
["f2544e2e"] = {name = "Ogre (Japan)"},
["b19e88aa"] = {name = "Ogre (Japan) (Alt)"},
["b1cb1052"] = {name = "Ouke no Tani - El Giza no Fuuin (Japan)"},
["774c70fc"] = {name = "Ouke no Tani - El Giza no Fuuin - Edit Contest Yuushuu Sakuhinshuu (Japan)"},
["0a9f8d6c"] = {name = "Out Run (Japan)"},
["7df16fc8"] = {name = "Pac-Mania (Japan)"},
["252798f6"] = {name = "Pachi Pro Densetsu (Japan)"},
["b1b24da1"] = {name = "Penguin-kun Wars 2 (Japan)"},
["70dc14a6"] = {name = "Penguin-kun Wars 2 (Japan) (Alt)"},
["e85a4a6b"] = {name = "Predator (Japan)"},
["356b7d2a"] = {name = "Pro Yakyuu Family Stadium - Pennant Race (Japan)"},
["c065bc29"] = {name = "Pro Yakyuu Fan - Telenet Stadium (Japan)"},
["2abb1ec4"] = {name = "Professional Mahjong Gokuu (Japan)"},
["1b285fe3"] = {name = "Project A2 - Shijousaidai no Hyouteki (Japan)"},
["6681d322"] = {name = "Quarth (Korea)"},
["c4ccb75f"] = {name = "Quarth (Japan) (Demo)"},
["a0014e7f"] = {name = "Quarth (Japan) (Wii U Virtual Console)"},
["8d94af7d"] = {name = "Quinpl (Japan)"},
["84461e73"] = {name = "Rastan Saga (Japan)"},
["babc68f2"] = {name = "Relics (Japan)"},
["6eee12c4"] = {name = "Replicart (Japan)"},
["8ee8212c"] = {name = "Return of Ishtar, The (Japan)"},
["5ccc09ab"] = {name = "Return of Jelda (Japan)"},
["e79aa962"] = {name = "Rick to Mick no Daibouken (Japan)"},
["fb9e42e1"] = {name = "Royal Blood (Japan)"},
["b83aa6f5"] = {name = "Sangokushi (Japan)"},
["c89b93b5"] = {name = "Sangokushi II (Japan)"},
["226795e0"] = {name = "Scramble Formation (Japan)"},
["e37b681e"] = {name = "Seikima II Special - Akuma no Gyakushuu (Japan)"},
["816aceb5"] = {name = "Seikima II Special - Akuma no Gyakushuu (Japan) (Alt)"},
["3b815dc6"] = {name = "Shanghai (Japan)"},
["39e1c37a"] = {name = "Shiryou Sensen - War of the Dead (Japan)"},
["27405eed"] = {name = "Space Manbow (Japan) (Wii U Virtual Console)"},
["441fc425"] = {name = "Star Virgin (Japan) (Alt)"},
["cbdfcc35"] = {name = "Star Virgin (Japan)"},
["4a3abb65"] = {name = "Strategic Mars (Japan)"},
["187d3a21"] = {name = "Suikoden - Tenmei no Chikai (Japan)"},
["8df9945a"] = {name = "Super Daisenryaku (Japan)"},
["80ecac11"] = {name = "Super Load Runner (Japan)"},
["b2392ef3"] = {name = "Super Rambo Special (Japan)"},
["5a5be701"] = {name = "Super Runner (Japan)"},
["cbb00ef1"] = {name = "Super Tritorn (Japan)"},
["7122e8e3"] = {name = "Synthe Saurus (Japan) (Program)"},
["ae82a874"] = {name = "Taiyou no Shinden - Asteka II (Japan)"},
["f640670c"] = {name = "Tanikawa Hiroshi no Shougi Shinan 2 (Japan)"},
["c31f459c"] = {name = "Teitoku no Ketsudan (Japan)"},
["7e637801"] = {name = "Tengoku Yoitoko (Japan)"},
["aa598dfd"] = {name = "Tetris (Japan)"},
["96b33497"] = {name = "Topple Zip (Japan)"},
["7372f63e"] = {name = "Treasure of the Usas (Japan) (Wii U Virtual Console)"},
["1f1f1f26"] = {name = "Treasure of Usas, The (Japan, Europe) (En) (Alt)"},
["30396650"] = {name = "Treasure of Usas, The (Japan, Europe) (En)"},
["ff7395a3"] = {name = "Tsurikichi Sanpei - Blue Marine Hen (Japan)"},
["24238b21"] = {name = "Tsurikichi Sanpei - Tsuri Sennin Hen (Japan)"},
["37b9e10f"] = {name = "Ultima Exodus (Japan)"},
["e564a25f"] = {name = "Urusei Yatsura - Koi no Survival Birthday (Japan)"},
["217935d0"] = {name = "Vampire Killer (Japan, Europe) (En) (Alt 3)"},
["0aedea40"] = {name = "Vampire Killer (Japan, Europe) (En) (Alt)"},
["038c250d"] = {name = "Vampire Killer (Japan, Europe) (En) (Alt 2)"},
["5953d084"] = {name = "Vampire Killer (Japan, Europe) (En)"},
["94ebc319"] = {name = "Victorious Nine II - Koukou Yakyuu Hen (Japan)"},
["08a5ca60"] = {name = "Wizardry (Japan)"},
["d1621bae"] = {name = "Woody Poco (Japan) (Alt)"},
["aea8d064"] = {name = "Woody Poco (Japan)"},
["97591725"] = {name = "Xevious - Fardraut Saga (Japan)"},
["21489e1d"] = {name = "Xevious - Fardraut Saga (Japan) (Alt)"},
["ff974ee3"] = {name = "Yaksa (Japan)"},
["dcb1a61e"] = {name = "Yamamura Misa Suspense - Kyoto Ryuu no Tera Satsujinjiken (Japan)"},
["712ae3c6"] = {name = "Yuurei-kun (Japan)"},
["d153b2f2"] = {name = "Zanac Ex (Japan)"},
["089c8164"] = {name = "Zanac Ex (Japan) (Alt)"},
["2605031e"] = {name = "Zoids - Chuuou Tairiku no Tatakai (Japan)"},
["a29e6ab4"] = {name = "Zombie Hunter (Japan)"},
["d0ececc6"] = {name = "Zukkoke Yajikita Onmitsu Douchuu (Japan)"},
["4968e84e"] = {name = "Zukkoke Yajikita Onmitsu Douchuu (Japan) (Alt)"},
}