return
{
["fde08d6d"] = {name = "1943 Kai (Japan)"},
["73614660"] = {name = "21 Emon - Mezase Hotel Ou!! (Japan)"},
["8e71d4f3"] = {name = "Adventure Island (Japan)"},
["25be2b81"] = {name = "Aero Blasters (Japan)"},
["b03e0b32"] = {name = "Aero Blasters (USA)"},
["ca72a828"] = {name = "After Burner II (Japan)"},
["933d5bcc"] = {name = "Air Zonk (USA)"},
["d76c4169"] = {name = "Air Zonk (USA, Europe) (Wii U Virtual Console)"},
["ea488494"] = {name = "Alien Crush (USA)"},
["60edf4e1"] = {name = "Alien Crush (Japan)"},
["04a85769"] = {name = "All Star Power League (Japan)"},
["a980e0e9"] = {name = "Andre Panza Kick Boxing (USA)"},
["cacc06fb"] = {name = "Ankoku Densetsu (Japan)"},
["08a09b9a"] = {name = "Aoi Blink (Japan)"},
["2b54cba2"] = {name = "Appare! Gateball (Japan)"},
["20ef87fd"] = {name = "Armed F (Japan)"},
["5e4fa713"] = {name = "Artist Tool (Japan)"},
["dd175efd"] = {name = "Atomic Robo-Kid Special (Japan)"},
["b866d282"] = {name = "AV Poker - World Gambler (Japan) (Unl)"},
["8acfc8aa"] = {name = "Ballistix (Japan)"},
["420fa189"] = {name = "Ballistix (USA)"},
["c267e25d"] = {name = "Bari Bari Densetsu (Japan)"},
["4a3df3ca"] = {name = "Barunba (Japan)"},
["106bb7b2"] = {name = "Batman (Japan)"},
["2cb92290"] = {name = "Battle Chopper (Japan)"},
["59e44f45"] = {name = "Battle Lode Runner (Japan)"},
["e70b01af"] = {name = "Battle Royale (USA)"},
["261f1013"] = {name = "Be Ball (Japan)"},
["e1a73797"] = {name = "Benkei Gaiden (Japan)"},
["c9626a43"] = {name = "Benkei Gaiden (Japan) (Wii Virtual Console)"},
["2841fd1e"] = {name = "Bikkuriman World (Japan)"},
["b4a1b0f6"] = {name = "Blazing Lazers (USA)"},
["e52be33e"] = {name = "Blazing Lazers (World) (Wii U Virtual Console)"},
["958bcd09"] = {name = "Blodia (Japan)"},
["37baf6bc"] = {name = "Bloody Wolf (USA)"},
["ffd92458"] = {name = "Bodycon Quest II (Japan) (Unl)"},
["5f6f3c2a"] = {name = "Bomberman (USA)"},
["9abb4d1f"] = {name = "Bomberman (Japan)"},
["3d1f8ece"] = {name = "Bomberman (USA) (Bomberman Collection)"},
["1489fa51"] = {name = "Bomberman - Users Battle (Japan)"},
["b300c5d0"] = {name = "Bomberman '93 (Japan)"},
["56171c1c"] = {name = "Bomberman '93 (USA)"},
["4c7ba73b"] = {name = "Bomberman '93 (USA, Europe) (Wii U Virtual Console)"},
["37c9114f"] = {name = "Bomberman '93 (Japan) (Wii U Virtual Console)"},
["02309aa0"] = {name = "Bomberman '93 - Special Version (Japan)"},
["05362516"] = {name = "Bomberman '94 (Japan)"},
["1aab222e"] = {name = "Bomberman '94 (World) (Wii U Virtual Console)"},
["5a3f76d8"] = {name = "Bonk 3 - Bonk's Big Adventure (USA)"},
["1f6511d7"] = {name = "Bonk 3 - Bonk's Big Adventure (USA, Europe) (Wii U Virtual Console)"},
["599ead9b"] = {name = "Bonk's Adventure (USA)"},
["704c801e"] = {name = "Bonk's Adventure (USA, Europe) (Wii U Virtual Console)"},
["f36ffee1"] = {name = "Bonk's Revenge (USA, Europe) (Wii Virtual Console)"},
["14250f9a"] = {name = "Bonk's Revenge (USA)"},
["2020817a"] = {name = "Bonk's Revenge (USA, Europe) (Wii U Virtual Console)"},
["8f4d9f94"] = {name = "Bouken Danshaku Don - The Lost Sunheart (Japan)"},
["605be213"] = {name = "Boxyboy (USA)"},
["cca08b02"] = {name = "Bravoman (USA)"},
["c9d7426a"] = {name = "Break In (Japan)"},
["0d766139"] = {name = "Bubblegum Crash! - Knight Sabers 2034 (Japan)"},
["5c4d1991"] = {name = "Bull Fight - Ring no Hasha (Japan)"},
["d233c05a"] = {name = "Burning Angels (Japan)"},
["d0c250ca"] = {name = "Busou Keiji - Cyber Cross (Japan)"},
["bb0b3aef"] = {name = "Cadash (USA)"},
["8dc0d85f"] = {name = "Cadash (Japan)"},
["9edc0aea"] = {name = "Champion Wrestler (Japan)"},
["15ee889a"] = {name = "Champions Forever Boxing (USA)"},
["9298254c"] = {name = "Chase H.Q. (USA)"},
["8cd13e9a"] = {name = "Chew-Man-Fu (USA)"},
["951ed380"] = {name = "Chibi Maruko-chan - Quiz de Piihyara (Japan)"},
["cab21b2e"] = {name = "Chikudenya Toubei - Kubikiri Yakata Yori (Japan)"},
["a2ee361d"] = {name = "China Warrior (USA)"},
["0df57c90"] = {name = "Chouzetsurinjin Bravoman (Japan)"},
["c3212c24"] = {name = "Circus Lido (Japan)"},
["f91b055f"] = {name = "City Hunter (Japan)"},
["99f7a572"] = {name = "Columns (Japan)"},
["b4d29e3b"] = {name = "Coryoon - Child of Dragon (Japan)"},
["9033e83a"] = {name = "Cratermaze (USA)"},
["2df97bd0"] = {name = "Cross Wiber - Cyber Combat Police (Japan)"},
["a98d276a"] = {name = "Cyber Core (Japan)"},
["b5326b16"] = {name = "Cyber Dodge (Japan)"},
["a594fac0"] = {name = "Cyber Knight (Japan)"},
["4cfb6e3e"] = {name = "Cyber-Core (USA)"},
["61a2935f"] = {name = "Daichi-kun Crisis - Do Natural (Japan)"},
["9107bcc8"] = {name = "Daisenpuu (Japan)"},
["b0ba689f"] = {name = "Darius Alpha (Japan) (SG Enhanced)"},
["eb2466f9"] = {name = "Darius Alpha (World) (SG Enhanced) (Darius Cozmic Collection)"},
["bebfe042"] = {name = "Darius Plus (Japan) (SG Enhanced)"},
["4ac97606"] = {name = "Darkwing Duck (USA)"},
["9edab596"] = {name = "Davis Cup Tennis (USA)"},
["f5d98b0b"] = {name = "Dead Moon (USA)"},
["56739bc7"] = {name = "Dead Moon - Getsu Sekai no Akumu (Japan)"},
["16b40b44"] = {name = "Deep Blue (USA)"},
["053a0f83"] = {name = "Deep Blue - Kaitei Shinwa (Japan)"},
["5cf59d80"] = {name = "Detana!! TwinBee (Japan)"},
["4ec81a80"] = {name = "Devil Crash - Naxat Pinball (Japan)"},
["38bbb515"] = {name = "Devil Crash - Naxat Pinball (Japan) (Wii U Virtual Console)"},
["157b4492"] = {name = "Devil's Crush (USA)"},
["6308eb07"] = {name = "Devil's Crush (USA, Europe) (Wii U Virtual Console)"},
["1b5b1cb1"] = {name = "Die Hard (Japan)"},
["17ba3032"] = {name = "Digital Champ (Japan)"},
["f42aa73e"] = {name = "Don Doko Don! (Japan)"},
["dc760a07"] = {name = "Doraemon - Meikyuu Daisakusen (Japan)"},
["013a747f"] = {name = "Doraemon - Nobita no Dorabian Night (Japan)"},
["4a1a8c60"] = {name = "Double Dungeons (USA)"},
["86087b39"] = {name = "Double Dungeons (Japan)"},
["d189b4ad"] = {name = "Double Dungeons (USA, Europe) (Wii U Virtual Console)"},
["d7bf80cc"] = {name = "Double Dungeons (Japan) (Wii U Virtual Console)"},
["85101c20"] = {name = "Down Load (Japan)"},
["442405d5"] = {name = "Dragon Egg! (Japan)"},
["3219849c"] = {name = "Dragon Saber (Japan)"},
["01a76935"] = {name = "Dragon Spirit (Japan)"},
["086f148c"] = {name = "Dragon Spirit (USA)"},
["7d2c4b09"] = {name = "Dragon's Curse (USA)"},
["fea27b32"] = {name = "Drop Off (USA)"},
["67ec5ec4"] = {name = "Drop Rock Hora Hora (Japan)"},
["1b1a80a2"] = {name = "Dungeon Explorer (Japan)"},
["4ff01515"] = {name = "Dungeon Explorer (USA)"},
["fae0fc60"] = {name = "Dungeons & Dragons - Order of the Griffon (USA)"},
["ca68ff21"] = {name = "Energy (Japan)"},
["b18d102d"] = {name = "Eternal City - Toshi Tensou Keikaku (Japan)"},
["d50ff730"] = {name = "F-1 Dream (Japan)"},
["09048174"] = {name = "F-1 Pilot - You're King of Kings (Japan)"},
["e14dee08"] = {name = "F1 Circus (Japan)"},
["d7cfd70f"] = {name = "F1 Circus '91 (Japan)"},
["b268f2a2"] = {name = "F1 Circus '92 - The Speed of Sound (Japan)"},
["13bf0409"] = {name = "F1 Triple Battle (Japan)"},
["0bc0a12b"] = {name = "Falcon (USA)"},
["e8c3573d"] = {name = "Fantasy Zone (USA)"},
["72cb0f9d"] = {name = "Fantasy Zone (Japan)"},
["4d3f879a"] = {name = "Fantasy Zone (Japan) (PC Engine Mini)"},
["1828d2e5"] = {name = "Fighting Run (Japan)"},
["c90971ba"] = {name = "Final Blaster (Japan)"},
["c8c084e3"] = {name = "Final Lap Twin (Japan)"},
["26408ea3"] = {name = "Final Lap Twin (USA)"},
["560d2305"] = {name = "Final Match Tennis (Japan)"},
["af2dd2af"] = {name = "Final Soldier (Japan) (En)"},
["06835d94"] = {name = "Final Soldier (World) (Wii U Virtual Console)"},
["02a578c5"] = {name = "Final Soldier - Special Version (Japan) (En)"},
["90ed6575"] = {name = "Fire Pro Wrestling - Combination Tag (Japan)"},
["e88987bb"] = {name = "Fire Pro Wrestling 2 - 2nd Bout (Japan)"},
["534e8808"] = {name = "Fire Pro Wrestling 3 - Legend Bout (Japan)"},
["85a1e7b6"] = {name = "Formation Soccer - Human Cup '90 (Japan)"},
["7146027c"] = {name = "Formation Soccer - On J League (Japan)"},
["12c4e6fd"] = {name = "Fushigi no Yume no Alice (Japan)"},
["95f90dec"] = {name = "Gai Flame (Japan)"},
["9182c639"] = {name = "Gai Flame (Japan) (Wii U Virtual Console)"},
["6fd6827c"] = {name = "Gaia no Monshou (Japan)"},
["1a8393c6"] = {name = "Galaga '88 (Japan)"},
["2909dec6"] = {name = "Galaga '90 (USA)"},
["27a4d11a"] = {name = "Ganbare! Golf Boys (Japan)"},
["e8702d51"] = {name = "Gekisha Boy (Japan)"},
["ad450dfc"] = {name = "Genji Tsuushin Agedama (Japan)"},
["b926c682"] = {name = "Genpei Toumaden (Japan)"},
["8793758c"] = {name = "Genpei Toumaden - Kan no Ni (Japan)"},
["2db4c1fd"] = {name = "Ghost Manor (USA)"},
["e749a22c"] = {name = "Gokuraku! Chuuka Taisen (Japan)"},
["4bd38f17"] = {name = "Gomola Speed (Japan)"},
["0517da65"] = {name = "Gradius (Japan)"},
["a5273cc4"] = {name = "Gradius (World) (Wii U Virtual Console)"},
["4eabdc5c"] = {name = "Gradius (Japan) (PC Engine Mini)"},
["f370b58e"] = {name = "Gunboat (USA)"},
["a17d4d7e"] = {name = "Gunhed (Japan)"},
["57f183ae"] = {name = "Gunhed - Special Version (Japan)"},
["ba4d0dd4"] = {name = "Hana Taaka Daka! (Japan)"},
["bf3e2cc7"] = {name = "Hanii in the Sky (Japan)"},
["9897fa86"] = {name = "Hanii on the Road (Japan)"},
["44e7df53"] = {name = "Hatris (Japan)"},
["eb923de5"] = {name = "Heavy Unit (Japan)"},
["1cab1ee6"] = {name = "Hisou Kihei X-SERD (Japan)"},
["8b29c3aa"] = {name = "Hit the Ice - VHL - The Official Video Hockey League (USA)"},
["7acb60c8"] = {name = "Hit the Ice - VHL - The Video Hockey League (Japan)"},
["b01ee703"] = {name = "Honoo no Toukyuuji - Dodge Danpei (Japan)"},
["9ec6fc6c"] = {name = "Idol Hanafuda Fan Club (Japan) (Unl)"},
["a80c565f"] = {name = "ImageFight (Japan)"},
["e2470f5f"] = {name = "Impossamole (USA)"},
["e01c5127"] = {name = "J.J. & Jeff (USA)"},
["0ad97b04"] = {name = "J.League Greatest Eleven (Japan)"},
["ea751e82"] = {name = "Jack Nicklaus - Championship Golf (Japan)"},
["83384572"] = {name = "Jack Nicklaus' Turbo Golf (USA)"},
["c6fa6373"] = {name = "Jackie Chan (Japan)"},
["9d2f6193"] = {name = "Jackie Chan's Action Kung Fu (USA)"},
["53109ae6"] = {name = "Jaseiken Necromancer (Japan)"},
["32c950be"] = {name = "Jaseiken Necromancer (Japan) (Wii Virtual Console)"},
["9aa5295c"] = {name = "Jaseiken Necromancer (World) (Wii U Virtual Console)"},
["cc7d3eeb"] = {name = "Jigoku Meguri (Japan)"},
["c150637a"] = {name = "Jinmu Denshou (Japan)"},
["c8c7d63e"] = {name = "Juuouki (Japan)"},
["a9084d6e"] = {name = "Kaizou Choujin Shubibinman (Japan)"},
["109ba474"] = {name = "Kaizou Choujin Shubibinman 2 - Aratanaru Teki (Japan)"},
["6069c5e7"] = {name = "Kato-chan Ken-chan (Japan)"},
["4f2844b0"] = {name = "Kattobi! Takuhai-kun (Japan)"},
["474d7a72"] = {name = "Keith Courage in Alpha Zones (USA)"},
["7e3c367b"] = {name = "KickBall (Japan)"},
["c0cb5add"] = {name = "Kiki Kaikai (Japan)"},
["2f2e2240"] = {name = "King of Casino (USA)"},
["bf52788e"] = {name = "King of Casino (Japan)"},
["c74ffbc9"] = {name = "Klax (Japan)"},
["0f1b59b4"] = {name = "Klax (USA)"},
["c614116c"] = {name = "Knight Rider Special (Japan)"},
["44f60137"] = {name = "Kore ga Pro Yakyuu '89 (Japan)"},
["1772b229"] = {name = "Kore ga Pro Yakyuu '90 (Japan)"},
["b552c906"] = {name = "Kung Fu, The (Japan)"},
["3872c2b3"] = {name = "Kung Fu, The (Japan) (Wii Virtual Console)"},
["02dde03e"] = {name = "Kyuukyoku Mahjong - Idol Graphics (Japan) (Unl)"},
["e5b6b3e5"] = {name = "Kyuukyoku Mahjong II (Japan) (Unl)"},
["09509315"] = {name = "Kyuukyoku Tiger (Japan)"},
["c6f764ec"] = {name = "Lady Sword - Ryakudatsu Sareta 10-nin no Otome (Japan) (Unl)"},
["3c131486"] = {name = "Legend of Hero Tonma (USA)"},
["c28b0d8a"] = {name = "Legend of Hero Tonma (Japan)"},
["220ebf91"] = {name = "Legendary Axe II (USA)"},
["2d211007"] = {name = "Legendary Axe, The (USA)"},
["e6ee1468"] = {name = "Lode Runner - Lost Labyrinth (Japan)"},
["a15a1f37"] = {name = "Maerchen Maze (Japan)"},
["dd0ebf8c"] = {name = "Magical Chase (Japan)"},
["95cd2979"] = {name = "Magical Chase (USA)"},
["f5b90d55"] = {name = "Mahjong Gakuen - Touma Soushirou Toujou (Japan)"},
["f4148600"] = {name = "Mahjong Gakuen Mild - Touma Soushirou Toujou (Japan)"},
["f8861456"] = {name = "Mahjong Gokuu Special (Japan)"},
["df10c895"] = {name = "Mahjong Haouden - Kaiser's Quest (Japan)"},
["6c34aaea"] = {name = "Mahjong Shikaku Retsuden - Mahjong Wars (Japan)"},
["5c78fee1"] = {name = "Maison Ikkoku (Japan)"},
["be62eef5"] = {name = "Makai Hakkenden Shada (Japan)"},
["b101b333"] = {name = "Makai Prince Dorabocchan (Japan)"},
["d4c5af46"] = {name = "Makyou Densetsu (Japan)"},
["99f2865c"] = {name = "Maniac Pro Wres - Asu e no Tatakai (Japan)"},
["2f8935aa"] = {name = "Mashin Eiyuuden Wataru (Japan)"},
["e87190f1"] = {name = "Mesopotamia (Japan)"},
["25a02bee"] = {name = "Metal Stoker (Japan)"},
["93f316f7"] = {name = "Military Madness (USA)"},
["b2ef558d"] = {name = "Mizubaku Daibouken (Japan)"},
["f860455c"] = {name = "Momotarou Densetsu Gaiden - Dai-1-shuu (Japan)"},
["d9e1549a"] = {name = "Momotarou Densetsu II (Japan)"},
["625221a6"] = {name = "Momotarou Densetsu Turbo (Japan)"},
["345f43e9"] = {name = "Momotarou Katsugeki (Japan)"},
["f2e46d25"] = {name = "Monster Pro Wres (Japan)"},
["2546efe0"] = {name = "Morita Shougi PC (Japan)"},
["e2b0d544"] = {name = "Moto Roader (USA)"},
["428f36cd"] = {name = "Moto Roader (Japan)"},
["0b7f6e5f"] = {name = "Moto Roader II (Japan)"},
["b01f70c2"] = {name = "Narazumono Sentou Butai - Bloody Wolf (Japan)"},
["60ecae22"] = {name = "Naxat Open (Japan)"},
["20a7d128"] = {name = "Naxat Stadium (Japan)"},
["0441d85a"] = {name = "Nazo no Mascarade (Japan)"},
["fb0fdcfe"] = {name = "Necros no Yousai (Japan)"},
["0243453b"] = {name = "Nectaris (Japan)"},
["65fdb863"] = {name = "Nekketsu Koukou Dodgeball-bu - PC Bangai Hen (Japan)"},
["f2285c6d"] = {name = "Nekketsu Koukou Dodgeball-bu - PC Soccer Hen (Japan)"},
["9c49ef11"] = {name = "Neutopia (Japan)"},
["a9a94e1b"] = {name = "Neutopia (USA)"},
["811259e5"] = {name = "Neutopia (USA, Europe) (Wii U Virtual Console)"},
["c8072f2d"] = {name = "Neutopia (Japan) (Wii U Virtual Console)"},
["c4ed4307"] = {name = "Neutopia II (USA)"},
["2b94aedc"] = {name = "Neutopia II (Japan)"},
["2602eda2"] = {name = "Neutopia II (USA, Europe) (Wii U Virtual Console)"},
["769aabc3"] = {name = "Neutopia II (Japan) (Wii U Virtual Console)"},
["756a1802"] = {name = "New Adventure Island (USA)"},
["21db1d10"] = {name = "New Adventure Island (USA, Europe) (Wii U Virtual Console)"},
["8e4d75a8"] = {name = "NewZealand Story, The (Japan)"},
["a32430d5"] = {name = "NHK Taiga Drama - Taiheiki (Japan)"},
["c159761b"] = {name = "Night Creatures (USA)"},
["82def9ee"] = {name = "Niko Niko Pun (Japan)"},
["67573bac"] = {name = "Ninja Ryuukenden (Japan)"},
["de8af1c1"] = {name = "Ninja Spirit (USA)"},
["85d1e33b"] = {name = "Ninja Spirit (USA, Europe) (Wii U Virtual Console)"},
["96e0cd9d"] = {name = "Ninja Warriors, The (Japan)"},
["4d3b0bc9"] = {name = "Obocchama-kun (Japan)"},
["8621ae02"] = {name = "Off the Wall (USA) (Proto)"},
["ff898f87"] = {name = "Operation Wolf (Japan)"},
["8c565cb6"] = {name = "Ordyne (Japan)"},
["e7bf2a74"] = {name = "Ordyne (USA)"},
["5cdb3f5b"] = {name = "Out Live (Japan)"},
["e203f223"] = {name = "Out Run (Japan)"},
["b74ec562"] = {name = "Override (Japan)"},
["7632db90"] = {name = "P-47 - The Freedom Fighter (Japan)"},
["d6e30ccd"] = {name = "Pac-Land (USA)"},
["14fad3ba"] = {name = "Pac-Land (Japan)"},
["4148fd7c"] = {name = "Pachio-kun - Juuban Shoubu (Japan)"},
["9893e0e6"] = {name = "Paranoia (Japan)"},
["51e86451"] = {name = "Parasol Stars - The Story of Bubble Bobble III (Japan)"},
["e6458212"] = {name = "Parasol Stars - The Story of Bubble Bobble III (USA)"},
["647718f9"] = {name = "Parodius Da! - Shinwa kara Owarai e (Japan)"},
["740491c2"] = {name = "PC Denjin - Punkic Cyborgs (Japan)"},
["4f8299c8"] = {name = "PC Denjin - Punkic Cyborgs (Japan) (Beta)"},
["51982ce2"] = {name = "PC Denjin - Punkic Cyborgs (Japan) (Wii U Virtual Console)"},
["2cb5cd55"] = {name = "PC Genjin - Pithecanthropus Computerurus (Japan)"},
["9c1f39db"] = {name = "PC Genjin - Pithecanthropus Computerurus (Japan) (Wii U Virtual Console)"},
["3028f7ca"] = {name = "PC Genjin 2 - Pithecanthropus Computerurus (Japan)"},
["d4ce3572"] = {name = "PC Genjin 2 - Pithecanthropus Computerurus (Japan) (Wii Virtual Console)"},
["34190272"] = {name = "PC Genjin 2 - Pithecanthropus Computerurus (Japan) (Wii U Virtual Console)"},
["a170b60e"] = {name = "PC Genjin 3 - Pithecanthropus Computerurus (Japan)"},
["6f6ed301"] = {name = "PC Genjin 3 - Pithecanthropus Computerurus (Japan) (Sample)"},
["e42ad101"] = {name = "PC Genjin 3 - Pithecanthropus Computerurus (Japan) (Wii U Virtual Console)"},
["0aa88f33"] = {name = "PC Pachi-Slot - Idol Gambler (Japan) (Unl)"},
["083c956a"] = {name = "Populous (Japan)"},
["25e0f6e9"] = {name = "Power Drift (Japan)"},
["3e647d8b"] = {name = "Power Eleven (Japan)"},
["be8b6e3b"] = {name = "Power Gate (Japan)"},
["ed1d3843"] = {name = "Power Golf (USA)"},
["ea324f07"] = {name = "Power Golf (Japan)"},
["69180984"] = {name = "Power League (Japan)"},
["7d3e6f33"] = {name = "Power League '93 (Japan)"},
["30cc3563"] = {name = "Power League 4 (Japan)"},
["8b61e029"] = {name = "Power League 5 (Japan)"},
["c5fdfa89"] = {name = "Power League II (Japan)"},
["8aa4b220"] = {name = "Power League III (Japan)"},
["29eec024"] = {name = "Power Sports (Japan)"},
["95830103"] = {name = "Power Sports (Japan) (Wii U Virtual Console)"},
["8def5aa1"] = {name = "Power Tennis (Japan)"},
["11a36745"] = {name = "Pro Tennis - World Court (Japan)"},
["34e089a9"] = {name = "Pro Yakyuu World Stadium (Japan)"},
["66b167a9"] = {name = "Pro Yakyuu World Stadium '91 (Japan)"},
["03883ee8"] = {name = "Psycho Chaser (Japan)"},
["6cc10824"] = {name = "Psychosis (USA)"},
["faa6e187"] = {name = "Puzzle Boy (Japan)"},
["965c95b3"] = {name = "Puzznic (Japan)"},
["f2e6856d"] = {name = "Quiz Toukou Shashin (Japan) (Unl)"},
["91ce5156"] = {name = "R-Type (USA)"},
["cec3d28a"] = {name = "R-Type I (Japan)"},
["417b961d"] = {name = "R-Type II (Japan) (v1.1)"},
["f207ecae"] = {name = "R-Type II (Japan)"},
["d8373de6"] = {name = "Rabio Lepus Special (Japan)"},
["3e79734c"] = {name = "Racing Damashii (Japan)"},
["850829f2"] = {name = "Raiden (Japan)"},
["bc59c31e"] = {name = "Raiden (USA)"},
["00c38e69"] = {name = "Rastan Saga II (Japan)"},
["2fd65312"] = {name = "Rock-On (Japan)"},
["91e6896f"] = {name = "Ryuukyuu (Japan)"},
["09a0bfcc"] = {name = "S.C.I. - Special Criminal Investigation (Japan)"},
["f999356f"] = {name = "Sadakichi Seven - Hideyoshi no Ougon (Japan)"},
["0590a156"] = {name = "Saigo no Nindou - Ninja Spirit (Japan)"},
["5ecbb3ac"] = {name = "Saigo no Nindou - Ninja Spirit (Japan) (Wii U Virtual Console)"},
["faecce20"] = {name = "Salamander (Japan)"},
["a869a0b4"] = {name = "Salamander (World) (Wii U Virtual Console)"},
["83b0c3a4"] = {name = "Salamander (Japan) (PC Engine Mini)"},
["77a924b7"] = {name = "Samurai-Ghost (USA)"},
["2e955051"] = {name = "Sekigahara (Japan)"},
["90e6bf49"] = {name = "Sengoku Mahjong (Japan)"},
["6923d736"] = {name = "Shanghai (Japan)"},
["bc655cf3"] = {name = "Shinobi (Japan)"},
["469a0fdf"] = {name = "Shiryou Sensen - War of the Dead (Japan)"},
["2774462c"] = {name = "Shockman (USA)"},
["23ec8970"] = {name = "Shougi Shodan Icchokusen (Japan)"},
["457f2bc4"] = {name = "Shougi Shoshinsha Muyou (Japan)"},
["d1993c9f"] = {name = "SideArms (USA)"},
["e5e7b8b7"] = {name = "SideArms - Hyper Dyne (Japan)"},
["616ea179"] = {name = "Silent Debuggers (Japan)"},
["fa7e5d66"] = {name = "Silent Debuggers (USA)"},
["b5c4eebd"] = {name = "Sindibad - Chitei no Daimakyuu (Japan)"},
["4f6e2dbd"] = {name = "Sinistron (USA)"},
["4d539c9f"] = {name = "Skweek (Japan)"},
["4bb68b13"] = {name = "Soldier Blade (USA)"},
["8420b12b"] = {name = "Soldier Blade (Japan)"},
["d2113bf1"] = {name = "Soldier Blade (USA, Europe) (Wii U Virtual Console)"},
["1d8701c9"] = {name = "Soldier Blade (Japan) (Wii U Virtual Console)"},
["f39f38ed"] = {name = "Soldier Blade - Special Version (Japan)"},
["8fcaf2e9"] = {name = "Somer Assault (USA)"},
["d7921df2"] = {name = "Son Son II (Japan)"},
["f74e5eb3"] = {name = "Sonic Spike - World Championship Beach Volleyball (USA)"},
["fb37ddc4"] = {name = "Soukoban World (Japan)"},
["64580427"] = {name = "Space Harrier (Japan)"},
["43b05eb8"] = {name = "Space Harrier (USA)"},
["99496db3"] = {name = "Space Invaders - Fukkatsu no Hi (Japan)"},
["1c6ff459"] = {name = "Spin Pair (Japan)"},
["a5290dd0"] = {name = "Spiral Wave (Japan)"},
["6b319457"] = {name = "Splatterhouse (Japan) (En)"},
["d00ca74f"] = {name = "Splatterhouse (USA)"},
["727f4656"] = {name = "Stratego (Japan)"},
["d15cb6bb"] = {name = "Street Fighter II' - Champion Edition (Japan)"},
["d6fc51ce"] = {name = "Strip Fighter II (Japan) (Unl)"},
["56488b36"] = {name = "Super Metal Crusher (Japan)"},
["69d52e7a"] = {name = "Super Momotarou Dentetsu (Japan) (Alt)"},
["3eb5304a"] = {name = "Super Momotarou Dentetsu (Japan)"},
["2bc023fc"] = {name = "Super Momotarou Dentetsu II (Japan)"},
["5d0e3105"] = {name = "Super Star Soldier (Japan)"},
["db29486f"] = {name = "Super Star Soldier (USA)"},
["0fca781a"] = {name = "Super Star Soldier (USA, Europe) (Wii U Virtual Console)"},
["71a5a90b"] = {name = "Super Star Soldier (Japan) (Wii U Virtual Console)"},
["ce2e4f9f"] = {name = "Super Volley Ball (Japan)"},
["245040b3"] = {name = "Super Volleyball (USA)"},
["cf73d8fc"] = {name = "Susanoou Densetsu (Japan)"},
["6f4fd790"] = {name = "Taito Chase H.Q. (Japan)"},
["e415ea19"] = {name = "Takahashi Meijin no Shin Bouken-jima (Japan)"},
["b0a4ef0b"] = {name = "Takahashi Meijin no Shin Bouken-jima (Japan) (Wii U Virtual Console)"},
["f022be13"] = {name = "Takeda Shingen (Japan)"},
["e9d51797"] = {name = "Takin' It to the Hoop (USA)"},
["bae9cecc"] = {name = "TaleSpin (USA)"},
["a6088275"] = {name = "Tatsujin (Japan)"},
["c1b26659"] = {name = "Tatsujin (Japan) (Beta)"},
["eeb6dd43"] = {name = "Tatsunoko Fighter (Japan)"},
["3b3808bd"] = {name = "Ten no Koe Bank (Japan)"},
["2e278ccb"] = {name = "Tenseiryuu - Saint Dragon (Japan)"},
["1b2d0077"] = {name = "Terra Cresta II - Mandoler no Gyakushuu (Japan)"},
["ddc3e809"] = {name = "Thunder Blade (Japan)"},
["985d492d"] = {name = "Tiger Road (USA)"},
["02c39660"] = {name = "Time Cruise (USA)"},
["cfec1d6a"] = {name = "Time Cruise II (Japan)"},
["5d395019"] = {name = "Timeball (USA)"},
["d20f382f"] = {name = "Titan (Japan)"},
["53b7784b"] = {name = "Toilet Kids (Japan)"},
["82ae3b16"] = {name = "Tora e no Michi (Japan)"},
["72e00bc4"] = {name = "Tower of Druaga, The (Japan)"},
["97c5ee9a"] = {name = "Toy Shop Boys (Japan)"},
["3aea2f8f"] = {name = "Tricky (Japan)"},
["48e6fd34"] = {name = "Tricky Kick (USA)"},
["61a6e210"] = {name = "Tsuppari Oozumou - Heisei Ban (Japan)"},
["f70112e5"] = {name = "Tsuru Teruhito no Jissen Kabushiki Bai Bai Game (Japan)"},
["eb045edf"] = {name = "Turrican (USA)"},
["b6b38d61"] = {name = "TV Sports Baseball (USA) (Proto)"},
["ea54d653"] = {name = "TV Sports Basketball (USA)"},
["10b60601"] = {name = "TV Sports Basketball (Japan)"},
["5e25b557"] = {name = "TV Sports Football (USA)"},
["968d908a"] = {name = "TV Sports Football (Japan)"},
["97fe5bcf"] = {name = "TV Sports Hockey (USA)"},
["e7529890"] = {name = "TV Sports Hockey (Japan)"},
["1cad4b7f"] = {name = "USA Pro Basketball (Japan)"},
["a3303978"] = {name = "Valkyrie no Densetsu (Japan)"},
["99d14fb7"] = {name = "Veigues - Tactical Gladiator (USA)"},
["04188c5c"] = {name = "Veigues - Tactical Gladiator (Japan)"},
["85cbd045"] = {name = "Victory Run (USA)"},
["aac2876f"] = {name = "Victory Run (USA, Europe) (Wii U Virtual Console)"},
["03e28cff"] = {name = "Victory Run - Eikou no 13,000km (Japan)"},
["2cebdbd5"] = {name = "Victory Run - Eikou no 13,000km (Japan) (Wii U Virtual Console)"},
["e4124fe0"] = {name = "Vigilante (Japan)"},
["79d49a0d"] = {name = "Vigilante (USA)"},
["1bc36b36"] = {name = "Violent Soldier (Japan)"},
["ad226f30"] = {name = "Volfied (Japan)"},
["be990010"] = {name = "W-Ring - The Double Rings (Japan)"},
["a2a0776e"] = {name = "Wai Wai Mahjong - Yukai na Janyuu-tachi (Japan)"},
["0112d0c7"] = {name = "Wallaby!! - Usagi no Kuni no Kangaroo Race (Japan)"},
["7d023b19"] = {name = "Wallaby!! - Usagi no Kuni no Kangaroo Race (Japan) (Wii U Virtual Console)"},
["9b5ebc58"] = {name = "Winning Shot (Japan)"},
["59d07314"] = {name = "Wonder Momo (Japan)"},
["be850530"] = {name = "World Beach Volley (Japan)"},
["b3eeea2e"] = {name = "World Circuit (Japan)"},
["61b3c8c8"] = {name = "World Class Baseball (USA, Europe) (Wii Virtual Console)"},
["4186d0c0"] = {name = "World Class Baseball (USA)"},
["a4457df0"] = {name = "World Court Tennis (USA)"},
["a9ab2954"] = {name = "World Jockey (Japan)"},
["4b93f0ac"] = {name = "World Sports Competition (USA)"},
["9aeb5d26"] = {name = "World Sports Competition (USA, Europe) (Wii U Virtual Console)"},
["f8f85eec"] = {name = "Xevious - Fardraut Saga (Japan)"},
["3ca7db48"] = {name = "Yo, Bro (USA)"},
["c0905ca9"] = {name = "You-You Jinsei (Japan)"},
["80c3f824"] = {name = "Youkai Douchuuki (Japan)"},
["ee156721"] = {name = "Zero4 Champ (Japan)"},
["b77f2e2f"] = {name = "Zero4 Champ (Japan) (Alt)"},
["67aab7a1"] = {name = "Zipang (Japan)"},
}