return
{
["c575a831"] = {name = "2010 - The Graphic Action Game (USA)"},
["3657f3cd"] = {name = "2010 - The Graphic Action Game (USA) (Beta)"},
["db845695"] = {name = "A.E. (USA) (Proto)"},
["51fe49c8"] = {name = "Activision Decathlon, The (USA)"},
["164c8c26"] = {name = "Adam's Musicbox Demo (USA) (Demo)"},
["fce3aa06"] = {name = "Alcazar - The Forgotten Fortress (USA)"},
["4ffb4e8c"] = {name = "Alphabet Zoo (USA)"},
["78a738af"] = {name = "Amazing Bumpman (USA)"},
["275c800e"] = {name = "Antarctic Adventure (USA, Europe)"},
["a66e5ed1"] = {name = "Antarctic Adventure (USA, Europe) (Beta)"},
["947437ec"] = {name = "Aquattack (USA)"},
["6f88fcf0"] = {name = "Artillery Duel (USA)"},
["4359a3e5"] = {name = "BC's Quest for Tires (USA)"},
["0ae39f2c"] = {name = "BC's Quest for Tires (Canada)"},
["1ca853d5"] = {name = "BC's Quest for Tires II - Grog's Revenge (Canada)"},
["d464e5e4"] = {name = "BC's Quest for Tires II - Grog's Revenge (USA)"},
["7a93c6e5"] = {name = "Beamrider (USA)"},
["18864abc"] = {name = "Berenstain Bears, The (USA) (Demo)"},
["df65fc87"] = {name = "Blockade Runner (USA)"},
["9b547ba8"] = {name = "Boulder Dash (USA)"},
["1796de5e"] = {name = "Boulder Dash (USA) (Beta)"},
["829c967d"] = {name = "Brain Strainers (USA)"},
["00b37475"] = {name = "Buck Rogers - Planet of Zoom (USA, Europe)"},
["eb498f97"] = {name = "Bump 'n' Jump (USA, Europe) (Beta)"},
["9e1fab59"] = {name = "Bump 'n' Jump (USA, Europe)"},
["e5c5ea20"] = {name = "BurgerTime (USA, Europe) (Beta)"},
["91346341"] = {name = "BurgerTime (USA, Europe)"},
["6af19e75"] = {name = "Cabbage Patch Kids - Adventures in the Park (USA, Europe)"},
["beacbff5"] = {name = "Cabbage Patch Kids - Adventures in the Park (USA, Europe) (Beta 1)"},
["5da13dfd"] = {name = "Cabbage Patch Kids - Adventures in the Park (USA, Europe) (Beta 2)"},
["75b08d99"] = {name = "Cabbage Patch Kids - Picture Show (USA)"},
["5aa22d66"] = {name = "Campaign '84 (USA)"},
["70f315c2"] = {name = "Carnival (USA, Europe)"},
["07a3d3db"] = {name = "Castelo (Brazil) (En) (Unl)"},
["13886c96"] = {name = "CAT S.O.S. Game, The (USA) (Promo)"},
["17edbfd4"] = {name = "Centipede (USA)"},
["030e0d48"] = {name = "Choplifter! (USA)"},
["5eeb81de"] = {name = "Chuck Norris - Superkicks (USA)"},
["71ae16ed"] = {name = "ColecoVision Monitor Test (USA, Europe)"},
["4e8b4c1d"] = {name = "Congo Bongo (USA)"},
["39d4215b"] = {name = "Cosmic Avenger (USA, Europe)"},
["7c2c7c41"] = {name = "Cosmic Crisis (Europe)"},
["c75fad5a"] = {name = "Dam Busters, The (Canada)"},
["890682b3"] = {name = "Dam Busters, The (USA)"},
["bff86a98"] = {name = "Dance Fantasy (USA)"},
["6cf594e5"] = {name = "Defender (USA)"},
["46a909cc"] = {name = "Defender (USA) (BUG Fixed)"},
["56c358a6"] = {name = "Destructor (USA, Europe)"},
["1038e0a1"] = {name = "Dig Dug (USA) (Proto)"},
["3c77198c"] = {name = "Donkey Kong (USA, Europe) (v1.1)"},
["94c4cd4a"] = {name = "Donkey Kong (USA)"},
["fd11508d"] = {name = "Donkey Kong Junior (USA, Europe)"},
["109699e2"] = {name = "Dr. Seuss - Fix-Up the Mix-Up Puzzler (USA)"},
["da521d6d"] = {name = "Dragon's Lair (USA) (Proto)"},
["dcb8f9e8"] = {name = "Dragonfire (USA)"},
["4025ac94"] = {name = "Dukes of Hazzard, The (USA)"},
["afb90dcd"] = {name = "Energy Quiz (Canada) (En,Fr-CA) (1983-06-06) (Proto)"},
["3678ab6f"] = {name = "Escape from the Mindmaster (USA) (Proto)"},
["4cd4e185"] = {name = "Evolution (Canada)"},
["4c933007"] = {name = "Evolution (USA) (Unl)"},
["ec9dfb07"] = {name = "Facemaker (USA)"},
["8a731b38"] = {name = "Fall Guy (USA) (Proto)"},
["b3b767ae"] = {name = "Fathom (USA)"},
["3ae4b58c"] = {name = "Final Test Cartridge (USA)"},
["64ec761e"] = {name = "Fireman (USA) (Proto)"},
["9788bca7"] = {name = "Flipper Slipper (USA) (Unl)"},
["2a49f507"] = {name = "Flipper Slipper (USA, Europe)"},
["65bbbcb4"] = {name = "Fortune Builder (USA)"},
["964db3bc"] = {name = "Fraction Fever (USA)"},
["8615c6e8"] = {name = "Frantic Freddy (USA)"},
["3cacddfb"] = {name = "Frenzy (USA, Europe)"},
["798002a2"] = {name = "Frogger (USA)"},
["4229ea5a"] = {name = "Frogger II - ThreeeDeep! (USA)"},
["e98b6851"] = {name = "Frogger II - ThreeeDeep! (USA) (Beta) (1984-06-15)"},
["d0110137"] = {name = "Front Line (USA, Europe) (Standard Controller)"},
["e16e0917"] = {name = "Front Line (USA, Europe) (Super Action Controller)"},
["6a7a162a"] = {name = "Galaxian (USA)"},
["fdb75be6"] = {name = "Gateway to Apshai (USA, Europe)"},
["ff46becc"] = {name = "Gorf (USA, Europe)"},
["29fea563"] = {name = "Gust Buster (USA)"},
["27cbf26d"] = {name = "Gyruss (USA)"},
["b35d4dc9"] = {name = "Gyruss (USA) (Beta)"},
["685ab9b5"] = {name = "H.E.R.O. - Helicopter Emergency Rescue Operation (USA)"},
["987491ce"] = {name = "Heist, The (USA)"},
["2787516d"] = {name = "Illusions (USA)"},
["cc43ebf7"] = {name = "It's Only Rock 'N' Roll (USA)"},
["561f2530"] = {name = "James Bond 007 (USA)"},
["52228000"] = {name = "Joust (USA) (Proto)"},
["a5511418"] = {name = "Jukebox (USA)"},
["ef50e1c5"] = {name = "Julius Erving and Larry Bird Go - One-on-One (USA)"},
["060c69e8"] = {name = "Jumpman Junior (USA, Europe)"},
["58e886d2"] = {name = "Jungle Hunt (USA)"},
["8c7b7803"] = {name = "Ken Uston Blackjack-Poker (USA, Europe)"},
["69fc2966"] = {name = "Keystone Kapers (USA)"},
["2c3097b8"] = {name = "Lady Bug (USA, Europe)"},
["1641044f"] = {name = "Learning with Leeper (USA)"},
["918f12c0"] = {name = "Linking Logic (USA)"},
["d54c581b"] = {name = "Logic Levels (USA)"},
["6a2d637b"] = {name = "Looping (USA, Europe)"},
["fee15196"] = {name = "Lord of the Dungeon (USA) (Beta)"},
["fc95b302"] = {name = "M.A.S.H (Europe) (Proto)"},
["2277f82b"] = {name = "Masters of the Universe - The Power of He-Man (USA) (Proto)"},
["90007079"] = {name = "Matt Patrol (USA) (Proto)"},
["fbe12de7"] = {name = "Matt Patrol (USA) (Proto) (Alt)"},
["bab520ea"] = {name = "Memory Manor (USA)"},
["6a162c7d"] = {name = "Meteoric Shower (Europe)"},
["f37af58c"] = {name = "Miner 2049er Starring Bounty Bob (USA, Europe)"},
["b24f10fd"] = {name = "Miner 2049er Starring Bounty Bob (USA, Europe) (v1.1)"},
["d92b09c8"] = {name = "Monkey Academy (USA)"},
["d1e8df85"] = {name = "Monkey Academy (USA) (Beta)"},
["ced0d16e"] = {name = "Montezuma's Revenge (USA)"},
["8a303f5a"] = {name = "Moonsweeper (USA, Europe)"},
["0f4d800a"] = {name = "Motocross Racer (USA)"},
["c173bbec"] = {name = "Mountain King (USA)"},
["de47c29f"] = {name = "Mouse Trap (USA, Europe)"},
["461ab6ad"] = {name = "Mr. Do! (USA, Europe)"},
["546f2c54"] = {name = "Mr. Do!'s Castle (USA)"},
["4491a35b"] = {name = "Nova Blast (USA, Europe)"},
["6af8b439"] = {name = "Number Bumper (USA) (Beta)"},
["add10242"] = {name = "Oil's Well (USA)"},
["0a0511c7"] = {name = "Omega Race (USA, Europe)"},
["2cc6f4aa"] = {name = "Orbit (USA) (Proto)"},
["a40a07e8"] = {name = "Pac-Man (USA) (Proto)"},
["53b85e20"] = {name = "Pepper II (USA, Europe)"},
["851a455f"] = {name = "Pitfall II - Lost Caverns (USA)"},
["d4f180df"] = {name = "Pitfall! (USA)"},
["e627fcf0"] = {name = "Pitstop (USA)"},
["81be4f55"] = {name = "Pitstop (USA, Europe) (v1.1)"},
["a095454d"] = {name = "Popeye (USA)"},
["46fc1c00"] = {name = "Porky's (USA) (Proto)"},
["2ebf88c4"] = {name = "Power Lords - Quest for Volcan (USA) (Proto 2)"},
["6e58974e"] = {name = "Power Lords - Quest for Volcan (USA) (Proto 1)"},
["532f61ba"] = {name = "Q-bert (USA)"},
["79d90d26"] = {name = "Q-bert's Qubes (USA)"},
["eec81c42"] = {name = "Quest for Quintana Roo (USA)"},
["fe897f9c"] = {name = "River Raid (USA)"},
["cdb8d3cf"] = {name = "Robin Hood (USA)"},
["af885d76"] = {name = "Roc 'N Rope (USA, Europe)"},
["af49a0c3"] = {name = "Rock n' Bolt (USA)"},
["37f144d3"] = {name = "Rocky - Super Action Boxing (USA, Europe)"},
["0364fb81"] = {name = "Rolloverture (USA)"},
["8afd7db2"] = {name = "Root Beer Tapper (USA)"},
["3563286b"] = {name = "Sammy Lightfoot (USA)"},
["0ec63a5c"] = {name = "Sector Alpha (USA)"},
["4591f393"] = {name = "Sewer Sam (USA)"},
["df84ffb5"] = {name = "Sir Lancelot (USA)"},
["b37d48bd"] = {name = "Skiing (USA)"},
["53d2651c"] = {name = "Slither (USA, Europe)"},
["8871e9fd"] = {name = "Slurpy (USA)"},
["97c0382d"] = {name = "Smurf - Paint 'n' Play WORKSHOP (USA, Europe)"},
["42850379"] = {name = "Smurf - Rescue in Gargamel's Castle (USA, Europe)"},
["9a3b8587"] = {name = "Smurfs Save the Day (USA) (Demo)"},
["df8de30f"] = {name = "Space Fury (USA, Europe)"},
["5bdf2997"] = {name = "Space Panic (USA, Europe)"},
["a6401c46"] = {name = "Spectron (USA)"},
["36478923"] = {name = "Spy Hunter (USA)"},
["1969b9b7"] = {name = "Spy Hunter (USA) (Beta)"},
["ac92862d"] = {name = "Squish'em Featuring Sam (USA)"},
["ea3aa29e"] = {name = "Star Fire (USA) (Proto)"},
["95824f1e"] = {name = "Star Trek - Strategic Operations Simulator (USA)"},
["0e75b3bf"] = {name = "Star Wars - The Arcade Game (USA)"},
["d7febc67"] = {name = "Star Wars - The Arcade Game (USA) (Beta) (1984-04-12)"},
["153ac4ef"] = {name = "Steamroller (USA) (Proto)"},
["d247a1c8"] = {name = "Strike It! (Europe)"},
["a417f25f"] = {name = "Subroc (USA, Europe)"},
["b3bcf3f9"] = {name = "Super Action Baseball (USA)"},
["62619dc0"] = {name = "Super Action Football (USA)"},
["4d6c0458"] = {name = "Super Action Football (Europe)"},
["f84622d2"] = {name = "Super Cobra (USA)"},
["eb6cb4d8"] = {name = "Super Controller Tester (USA)"},
["84350129"] = {name = "Super Cross Force (USA, Europe)"},
["ef25af90"] = {name = "Super DK! (USA) (Proto)"},
["c2e7f0e0"] = {name = "Super DK! Junior (USA) (Proto)"},
["8627300a"] = {name = "Super Sketch - Sketch Master (USA) (Program) (Unl)"},
["8bda7c48"] = {name = "Sword and the Sorcerer, The (USA) (Demo)"},
["af6bbc7e"] = {name = "Tank Wars (Europe)"},
["7cd7a702"] = {name = "Tarzan (USA, Europe)"},
["c8bc1950"] = {name = "Telly Turtle (USA)"},
["1593f7df"] = {name = "Threshold (USA)"},
["b3a1eacb"] = {name = "Time Pilot (USA, Europe)"},
["1e14397e"] = {name = "TOMARC the Barbarian (USA)"},
["c1d5a702"] = {name = "Tournament Tennis (USA)"},
["291a0004"] = {name = "Tunnels & Trolls (USA) (Demo)"},
["bd6ab02a"] = {name = "Turbo (USA, Europe)"},
["0408f58c"] = {name = "Tutankham (USA)"},
["fdd52ca0"] = {name = "Up 'n Down (USA)"},
["8e5a4aa3"] = {name = "Venture (USA, Europe)"},
["70142655"] = {name = "Victory (USA)"},
["b1fda1c5"] = {name = "Victory (Europe)"},
["a9177b20"] = {name = "Video Hustler (USA) (Proto 2)"},
["841d168f"] = {name = "Video Hustler (USA) (Proto 1)"},
["261b7d56"] = {name = "War Room (USA)"},
["fd25adb3"] = {name = "WarGames (USA, Europe)"},
["29ec00c9"] = {name = "Wing War (USA)"},
["b9ba2bb6"] = {name = "Wizard of Id's - WizMath (USA)"},
["f7a29c01"] = {name = "Word Feud (USA)"},
["997ad8de"] = {name = "Yolk's on you, The (Europe) (Proto)"},
["8cb0891a"] = {name = "Zaxxon (USA, Europe)"},
["5b0e2adf"] = {name = "Zaxxon (Taiwan) (En) (Unl)"},
["6e523e50"] = {name = "Zenji (USA)"},
}