return
{
["be913cfa"] = {name = "Bakumatsu Rouman Tokubetsu Hen - Gekka no Kenshi - Tsuki ni Saku Hana, Chiri Yuku Hana (Japan)"},
["d1434df5"] = {name = "Baseball Stars Color - Pocket Sports Series (World) (En,Ja)"},
["f1716fdf"] = {name = "Big Bang Pro Wrestling (Japan) (En,Ja)"},
["7a2d7635"] = {name = "Bikkuriman 2000 - Viva! Pocket Festival! (Japan)"},
["fcbbe494"] = {name = "Biomotor Unitron (Japan)"},
["3807df4f"] = {name = "Biomotor Unitron (USA, Europe)"},
["6011dab0"] = {name = "Biomotor Unitron (Japan) (Demo)"},
["b073d601"] = {name = "Bust-A-Move Pocket (USA)"},
["78a1361d"] = {name = "Bust-A-Move Pocket (USA) (Beta)"},
["2ed72635"] = {name = "Cool Boarders Pocket (Japan, Europe) (En,Ja)"},
["0fd6f378"] = {name = "Cool Cool Jam (Japan)"},
["4d8d27f0"] = {name = "Cool Cool Jam (USA) (Proto)"},
["f20ff9f2"] = {name = "Crush Roller (World) (En,Ja)"},
["77caa548"] = {name = "Dark Arms - Beast Buster 1999 (World) (En,Ja)"},
["1273b10e"] = {name = "Delta Warp (Japan) (En,Ja)"},
["3bb899e8"] = {name = "Delta Warp (Japan) (Demo)"},
["eeeefd6a"] = {name = "Densetsu no Ogre Battle Gaiden - Zenobia no Ouji (Japan)"},
["a0334549"] = {name = "Densha de Go! 2 on NeoGeo Pocket (Japan)"},
["2fc4623e"] = {name = "Densha de Go! 2 on NeoGeo Pocket (Japan) (Demo)"},
["83db5772"] = {name = "Dive Alert - Becky's Version (USA, Europe)"},
["c213941d"] = {name = "Dive Alert - Burn Hen (Japan)"},
["d9817a88"] = {name = "Dive Alert - Burn Hen (Japan) (Beta)"},
["ef75081b"] = {name = "Dive Alert - Matt's Version (USA, Europe)"},
["3c4af4f5"] = {name = "Dive Alert - Rebecca Hen (Japan)"},
["78c21b5e"] = {name = "Dokodemo Mahjong (Japan)"},
["7f1779cd"] = {name = "Dynamite Slugger (Japan, Europe) (En,Ja)"},
["be47e531"] = {name = "Evolution - Eternal Dungeons (Europe) (vA1)"},
["a60582f8"] = {name = "Evolution - Eternal Dungeons (Europe) (v03)"},
["1bf412f5"] = {name = "Fantastic Night Dreams - Cotton (Europe)"},
["b8a12409"] = {name = "Fantastic Night Dreams - Cotton (Japan)"},
["e705e30e"] = {name = "Faselei! (USA, Europe)"},
["8f585838"] = {name = "Faselei! (Japan)"},
["e7e5d6e8"] = {name = "Fatal Fury F-Contact - Pocket Fighting Series (World) (En,Ja)"},
["6df986a3"] = {name = "Ganbare Neo Poke-kun (Kari) (Japan)"},
["32dc2aa2"] = {name = "Infinity Cure (Japan)"},
["f029f1c0"] = {name = "Kikou Seiki Unitron - Sono Tsuide. Hikari Umareru Chi Yori. (Japan)"},
["9bc63f27"] = {name = "King of Fighters R-2 - Pocket Fighting Series (World) (En,Ja)"},
["e3ae79c0"] = {name = "King of Fighters R-2 - Pocket Fighting Series (Japan) (En,Ja) (Demo 1)"},
["76544c97"] = {name = "King of Fighters R-2 - Pocket Fighting Series (Japan) (En,Ja) (Demo 2)"},
["77e37bac"] = {name = "King of Fighters, The - Battle de Paradise (Japan)"},
["b51c3eba"] = {name = "Koi Koi Mahjong (Japan) (v0B)"},
["75fe164c"] = {name = "Koi Koi Mahjong (Japan) (v08)"},
["94fcfd1e"] = {name = "Last Blade, The - Beyond the Destiny (USA, Europe)"},
["694ce2dc"] = {name = "Magical Drop Pocket (Japan)"},
["7712f82d"] = {name = "Magical Drop Pocket (USA, Europe)"},
["d76f1a47"] = {name = "Magical Drop Pocket (Japan) (Demo)"},
["7f919dde"] = {name = "Memories Off - Pure (Japan)"},
["d29ec1ba"] = {name = "Metal Slug - 1st Mission (World) (En,Ja)"},
["18e692a5"] = {name = "Metal Slug - 2nd Mission (World) (En,Ja)"},
["8b1647d4"] = {name = "Metal Slug - 2nd Mission (World) (En,Ja) (Demo)"},
["a52e1c82"] = {name = "Mezase! Kanji Ou (Japan)"},
["dde08335"] = {name = "Mizuki Shigeru no Youkai Shashinkan (Japan)"},
["95c38985"] = {name = "Neo 21 - Pocket Casino Series (World)"},
["22aab454"] = {name = "Neo Baccarat - Pocket Casino Series (Japan, Europe) (En) (v16)"},
["80880498"] = {name = "Neo Baccarat - Pocket Casino Series (Japan, Europe) (En) (Beta)"},
["c8be28c0"] = {name = "Neo Baccarat - Pocket Casino Series (Japan, Europe) (En) (v11)"},
["2f6eb991"] = {name = "Neo Cherry Master Color - Pocket Casino Series (World) (En,Ja)"},
["1a288507"] = {name = "Neo Cherry Master Color - Pocket Casino Series (World) (En,Ja) (Demo)"},
["4760564a"] = {name = "Neo Derby Champ Daiyosou (Japan)"},
["225fd7f9"] = {name = "Neo Dragon's Wild - Real Casino Series (World) (En,Ja) (v11)"},
["5d028c99"] = {name = "Neo Dragon's Wild - Real Casino Series (World) (En,Ja) (v13)"},
["e79dc5b3"] = {name = "Neo Mystery Bonus - Pocket Casino Series (World) (En,Ja)"},
["c624388f"] = {name = "Neo Poke Pro Yakyuu (Japan) (v32)"},
["3ca883a5"] = {name = "Neo Poke Pro Yakyuu (Japan) (v1F)"},
["e0e853dd"] = {name = "Neo Turf Masters (World) (En,Ja)"},
["c0da4fe9"] = {name = "NeoGeo Cup '98 Plus Color - Pocket Sports Series (World) (En,Ja)"},
["a9063d9e"] = {name = "Nige-ron-pa (Japan)"},
["a9118e82"] = {name = "Oekaki Puzzle (Japan)"},
["21e8cc15"] = {name = "Pac-Man (World) (En,Ja)"},
["96ddfbe3"] = {name = "Pachi-Slot Aruze Oukoku - Porcano 2 (Japan)"},
["25b783b5"] = {name = "Pachi-Slot Aruze Oukoku Pocket - Azteca (Japan) (v04)"},
["2314440a"] = {name = "Pachi-Slot Aruze Oukoku Pocket - Azteca (Japan) (v03)"},
["c9b55e6b"] = {name = "Pachi-Slot Aruze Oukoku Pocket - Azteca (Japan) (v06)"},
["346f3c46"] = {name = "Pachi-Slot Aruze Oukoku Pocket - Dekahel 2 (Japan)"},
["1ea69db1"] = {name = "Pachi-Slot Aruze Oukoku Pocket - Delsol 2 (Japan)"},
["0a7c32df"] = {name = "Pachi-Slot Aruze Oukoku Pocket - e-CUP (Japan) (v04)"},
["b5311753"] = {name = "Pachi-Slot Aruze Oukoku Pocket - e-CUP (Japan) (v03)"},
["4014ff42"] = {name = "Pachi-Slot Aruze Oukoku Pocket - Hanabi (Japan) (v03)"},
["a0c26f9b"] = {name = "Pachi-Slot Aruze Oukoku Pocket - Hanabi (Japan) (v05)"},
["2a4f45ab"] = {name = "Pachi-Slot Aruze Oukoku Pocket - Hanabi (Japan) (v04)"},
["8a88c50f"] = {name = "Pachi-Slot Aruze Oukoku Pocket - Ohanabi (Japan)"},
["d46cbc54"] = {name = "Pachi-Slot Aruze Oukoku Pocket - Ward of Lights (Japan) (v03)"},
["a54ec305"] = {name = "Pachi-Slot Aruze Oukoku Pocket - Ward of Lights (Japan) (v04)"},
["543dc257"] = {name = "Pachinko Hisshou Guide - Pocket Parlor (Japan)"},
["ccf07c2f"] = {name = "Pachinko Hisshou Guide - Pocket Parlor (Japan) (Beta)"},
["4da8a1c0"] = {name = "Party Mail (Japan)"},
["f2284a95"] = {name = "Party Mail (Japan) (Beta)"},
["6f2d35e6"] = {name = "Picture Puzzle (Europe)"},
["c2ee1ee5"] = {name = "Pocket Love - if (Japan)"},
["22c07c25"] = {name = "Pocket Reversi (Europe) (vA1)"},
["d115fedf"] = {name = "Pocket Reversi (Japan)"},
["9589f2f2"] = {name = "Pocket Reversi (Europe) (v03)"},
["e0b9aa22"] = {name = "Pocket Tennis Color - Pocket Sports Series (World) (En,Ja)"},
["78acdbcb"] = {name = "PP-AA01 - Pusher - Program - Hontai Controller Gawa (Japan)"},
["3090b2fd"] = {name = "Puyo Pop (World) (En,Ja) (v05)"},
["5c649d1e"] = {name = "Puyo Pop (World) (En,Ja) (v06)"},
["d31312dc"] = {name = "Puzzle Bobble Mini (Europe)"},
["d6544f6c"] = {name = "Puzzle Bobble Mini (Japan) (En)"},
["8d0610ac"] = {name = "Puzzle Link (USA, Europe)"},
["ba9ca21c"] = {name = "Puzzle Link 2 (USA, Europe)"},
["c3f3e83c"] = {name = "Renketsu Puzzle Tsunagete Pon! Color (Japan)"},
["3c010642"] = {name = "Rockman - Battle & Fighters (Japan)"},
["f0b27871"] = {name = "Rockman - Battle & Fighters (Japan) (Demo)"},
["58a62fb2"] = {name = "Samurai Shodown! 2 - Pocket Fighting Series (World) (En,Ja)"},
["90732d53"] = {name = "Shanghai Mini (World) (En,Ja)"},
["79620c3f"] = {name = "Shanghai Mini (World) (En,Ja) (Beta 1)"},
["920af0ed"] = {name = "Shanghai Mini (World) (En,Ja) (Beta 2)"},
["e006f42f"] = {name = "Shinki Sekai Evolution - Hateshinai Dungeon (Japan)"},
["1f2872ed"] = {name = "Shougi no Tatsujin Color (Japan)"},
["d73b5b9f"] = {name = "SNK Gals' Fighters (Japan)"},
["b02c2be7"] = {name = "SNK Gals' Fighters (USA, Europe)"},
["ccbcfda7"] = {name = "SNK vs. Capcom - Card Fighters 2 - Expand Edition (Japan)"},
["80ce137b"] = {name = "SNK vs. Capcom - Card Fighters' Clash - Capcom Version (USA, Europe)"},
["94b63a97"] = {name = "SNK vs. Capcom - Card Fighters' Clash - SNK Version (USA, Europe)"},
["4a41a56e"] = {name = "SNK vs. Capcom - Gekitotsu Card Fighters (Japan) (Demo)"},
["9217159b"] = {name = "SNK vs. Capcom - Gekitotsu Card Fighters - Capcom Supporter Version (Japan)"},
["7065295c"] = {name = "SNK vs. Capcom - Gekitotsu Card Fighters - SNK Supporter Version (Japan)"},
["1b28ac12"] = {name = "SNK vs. Capcom - Gekitotsu Card Fighters - SNK Supporter Version (Japan) (Demo)"},
["682a7a7b"] = {name = "SNK vs. Capcom - The Match of the Millennium (World) (En,Ja)"},
["1e19e307"] = {name = "SNK vs. Capcom - The Match of the Millennium (Japan) (Demo)"},
["8bd22145"] = {name = "Sonic The Hedgehog - Pocket Adventure (World) (En,Ja)"},
["189a9141"] = {name = "Sonic The Hedgehog - Pocket Adventure (World) (Demo)"},
["45fc3bca"] = {name = "Sonic The Hedgehog - Pocket Adventure (World) (Beta) (1999-10-22)"},
["05fa3eb0"] = {name = "Soreike!! Hanafuda Doujou (Japan)"},
["c6e620c3"] = {name = "Super Real Mahjong - Premium Collection (Japan)"},
["129091bb"] = {name = "Tsunagete Pon! 2 (Japan)"},
["16b0be9b"] = {name = "Wrestling Madness (Japan) (En) (Beta)"},
}