return
{
["a6a6ec51"] = {name = "3D Othello (World) (Ja) (WonderWitch) (Unl)"},
["b0a64ace"] = {name = "4 Koma TV (World) (Ja) (WonderWitch) (Unl)"},
["b18cdc0d"] = {name = "Alchemist Marie & Elie - Futari no Atelier (Japan)"},
["30ef908e"] = {name = "Alchemist Marie & Elie - Futari no Atelier (Japan) (Demo) (WonderWitch)"},
["d7a0ab74"] = {name = "Another Heaven - Memory of those Days (Japan)"},
["e2317345"] = {name = "Arc the Lad - Kishin Fukkatsu (Japan)"},
["4567fb44"] = {name = "Artisan (World) (WonderWitch) (Unl)"},
["758299f9"] = {name = "Arubi (World) (Ja) (v0.08) (Proto) (WonderWitch) (Unl)"},
["c1ce966f"] = {name = "Atchi Muite Hoitsu! (World) (Ja) (WonderWitch) (Unl)"},
["8ba49dab"] = {name = "Battle Spirit - Digimon Frontier (Japan) (Rev 1)"},
["99027238"] = {name = "Blue Wing Blitz (Japan)"},
["930d66aa"] = {name = "BOM Danna (World) (Ja) (WonderWitch) (Unl)"},
["43167bf8"] = {name = "Bury (World) (WonderWitch) (Unl)"},
["37738113"] = {name = "Canon Hockey (World) (WonderWitch) (Unl)"},
["8ca7bb6a"] = {name = "Chains (World) (WonderWitch) (Unl)"},
["deb9ad0f"] = {name = "Charaga (World) (WonderWitch) (Unl)"},
["09e82f48"] = {name = "Coar Crashers (World) (Demo) (WonderWitch) (Unl)"},
["4995eb60"] = {name = "Course Out 2 (World) (Ja) (v0.0.1) (WonderWitch) (Unl)"},
["1143a561"] = {name = "Course Out 3 (World) (Ja) (v0.0.1) (Proto) (WonderWitch) (Unl)"},
["12ae932c"] = {name = "Dark Eyes - Battle Gate (Japan)"},
["1e2b5421"] = {name = "Darkhero Figment - Calibur Edition (World) (Ja) (WonderWitch) (Unl)"},
["b518b51c"] = {name = "Darkhero Figment - Doris Edition (World) (Ja) (WonderWitch) (Unl)"},
["3951d2d0"] = {name = "Darkhero Figment 2 (World) (Ja) (WonderWitch) (Unl)"},
["1887389c"] = {name = "Dicing Knight. (Japan)"},
["77689273"] = {name = "Digimon - Anode Tamer & Cathode Tamer - Veedramon Version (Hong Kong) (En)"},
["7b2a02e3"] = {name = "Digimon - Anode Tamer & Cathode Tamer - Veedramon Version (Korea) (En)"},
["4d28637e"] = {name = "Digimon Adventure 02 - D1 Tamers (Japan)"},
["62f4e4b4"] = {name = "Digimon Adventure 02 - D1 Tamers (Japan) (Rev 1)"},
["c927bfcb"] = {name = "Digimon Tamers - Battle Spirit (Japan, Korea) (En,Ja)"},
["6caad4a2"] = {name = "Digimon Tamers - Battle Spirit Ver. 1.5 (Japan)"},
["f1f4d41f"] = {name = "Digimon Tamers - Brave Tamer (Japan) (Rev 1)"},
["fa92418d"] = {name = "Digimon Tamers - Digimon Medley (Japan)"},
["84a46949"] = {name = "Digimon Tamers - Digimon Medley (Japan) (Rev 1)"},
["faaefbcb"] = {name = "Digital Monster - D-Project (Japan)"},
["bd83b82d"] = {name = "Digital Monster - D-Project (Japan) (Rev 1)"},
["0e40829c"] = {name = "Digital Monster - D-Project (Japan) (Rev 2)"},
["603cb5e6"] = {name = "Digital Monster Card Game - Ver. WonderSwan Color (Japan)"},
["1e760c41"] = {name = "Digital Monster Card Game - Ver. WonderSwan Color (Japan) (Rev 2)"},
["93e19f13"] = {name = "Dokodemo Hamster 3 - Odekake Saffron (Japan) (Rev 2)"},
["067238d1"] = {name = "Dragon Ball (Japan)"},
["2b2835b3"] = {name = "Es=Loss Zero Side (World) (Ja) (Unl)"},
["3c995a4b"] = {name = "Features (World) (WonderWitch) (Unl)"},
["b7243e88"] = {name = "Final Fantasy (Japan)"},
["f09e752f"] = {name = "Final Fantasy II (Japan)"},
["f699d6d1"] = {name = "Final Fantasy IV (Japan)"},
["b07e6a56"] = {name = "Final Lap Special - GT & Formula Machine (Japan)"},
["69d8d433"] = {name = "Flash Koibito-kun (Japan)"},
["c071d240"] = {name = "Flash Masta Firmware (USA) (2016-08-29) (Unl)"},
["aabce377"] = {name = "Flash Masta Firmware (USA) (2016-05-13) (Unl)"},
["8111a9b1"] = {name = "Flip (World) (Proto) (WonderWitch) (Unl)"},
["8e120b5a"] = {name = "From TV Animation One Piece - Chopper no Daibouken (Japan)"},
["f8a1dd2b"] = {name = "From TV Animation One Piece - Grand Battle Swan Colosseum (Japan)"},
["23853305"] = {name = "From TV Animation One Piece - Grand Battle Swan Colosseum (Japan) (Sample)"},
["427056c4"] = {name = "From TV Animation One Piece - Niji no Shima Densetsu (Japan)"},
["205503c3"] = {name = "From TV Animation One Piece - Treasure Wars (Japan)"},
["3df3e34c"] = {name = "From TV Animation One Piece - Treasure Wars (Japan) (Rev 1)"},
["0d1048f0"] = {name = "From TV Animation One Piece - Treasure Wars 2 - Buggy Land e Youkoso (Japan)"},
["2f9e2560"] = {name = "Front Mission (Japan)"},
["c9c7ba79"] = {name = "Gansaku Shuu Watch (World) (Ja) (WonderWitch) (Unl)"},
["8a8b827c"] = {name = "Gekitou! Crash Gear Turbo - Gear Champion League (Japan)"},
["446e2581"] = {name = "Gensou Maden Saiyuuki Retribution - Hi no Ataru Basho de (Japan) (Rev 2)"},
["bc944a98"] = {name = "Golden Axe (Japan)"},
["982f57f7"] = {name = "GPS TOOL for WonderSwan (World) (Ja) (WonderWitch) (Unl)"},
["af24f95c"] = {name = "Gransta Chronicle (Japan)"},
["9750bc2a"] = {name = "Guilty Gear Petit (Japan)"},
["d7a12bd5"] = {name = "Guilty Gear Petit 2 (Japan)"},
["0c9cb12c"] = {name = "GunPey EX (Japan)"},
["11db7be0"] = {name = "Guruguru Ringuru (World) (WonderWitch) (Unl)"},
["c2f1a2ee"] = {name = "Hanabi (World) (Proto) (WonderWitch) (Unl)"},
["31e09bed"] = {name = "Hanjuku Hero - Ah, Sekai yo Hanjuku Nare...!! (Japan) (Rev 1)"},
["7a29e9a6"] = {name = "Hataraku Chocobo (Japan)"},
["11a3209e"] = {name = "Hebi (World) (Ja) (WonderWitch) (Unl)"},
["a465b49b"] = {name = "HG-voice-player + Sound Sample (World) (WonderWitch) (Program) (Unl)"},
["66dc64ac"] = {name = "Hirotte, Yokete!! (World) (WonderWitch) (Unl)"},
["d9c701a4"] = {name = "Hoippuru for WonderSwan (World) (Ja) (v2.00) (WonderWitch) (Unl)"},
["73ae8016"] = {name = "House Keeper (World) (Ja) (WonderWitch) (Unl)"},
["8393480d"] = {name = "House Keeper - 1.5 Generation (World) (Ja) (Proto) (WonderWitch) (Unl)"},
["a487b7a8"] = {name = "Hunter X Hunter - Greed Island (Japan)"},
["130af567"] = {name = "Hunter X Hunter - Greed Island (Japan) (Rev 1)"},
["9402bca9"] = {name = "Hunter X Hunter - Michibikareshi Mono (Japan)"},
["d0b20c5a"] = {name = "Hunter X Hunter - Sorezore no Ketsui (Japan)"},
["84ca6856"] = {name = "Hurry Up! (World) (WonderWitch) (Unl)"},
["5e383ec0"] = {name = "Ice Cream Shop (World) (WonderWitch) (Unl)"},
["1fbd22dd"] = {name = "Illusion Garden (World) (Ja) (WonderWitch) (Unl)"},
["cca71dce"] = {name = "Inu Renda 2 (World) (Ja) (WonderWitch) (Unl)"},
["3ff5791f"] = {name = "Inuyasha - Fuuun Emaki (Japan)"},
["0c23d551"] = {name = "Inuyasha - Kagome no Sengoku Nikki (Japan)"},
["44453234"] = {name = "Inuyasha - Kagome no Yume Nikki (Japan)"},
["ffe8cee7"] = {name = "Isigarki (World) (WonderWitch) (Program) (Unl)"},
["3884dd9f"] = {name = "Isomon - Get Oh No!! (World) (Ja) (WonderWitch) (Unl)"},
["c2918548"] = {name = "Judgement Silversword (World) (Ja) (WonderWitch) (Unl)"},
["aa13e9de"] = {name = "Judgement Silversword - Rebirth Edition (Japan) (Rev 4321)"},
["85c4c9a1"] = {name = "Judgement Silversword - Rebirth Edition (Japan) (Rev 5C21)"},
["858ac811"] = {name = "Juicy Crew (World) (WonderWitch) (Unl)"},
["f3e39740"] = {name = "Kaikon (World) (Ja) (WonderWitch) (Unl)"},
["0b24a1cd"] = {name = "Kanain (World) (Ja) (WonderWitch) (Unl)"},
["efa0d4b1"] = {name = "Kasanegasane (World) (Ja) (WonderWitch) (Unl)"},
["d4061551"] = {name = "Kidou Senshi Gundam - Giren no Yabou - Tokubetsu Hen - Aoki Hoshi no Hasha (Japan)"},
["bce15137"] = {name = "Kidou Senshi Gundam Seed (Japan)"},
["08c0247b"] = {name = "Kidou Senshi Gundam Vol. 1 - Side 7 (Japan)"},
["39a1391a"] = {name = "Kidou Senshi Gundam Vol. 2 - Jaburo (Japan)"},
["a9f5bf54"] = {name = "Kidou Senshi Gundam Vol. 3 - A Baoa Qu (Japan)"},
["6142fd9d"] = {name = "Kinnikuman II-Sei - Choujin Seisenshi (Japan)"},
["462f9275"] = {name = "Kinnikuman II-Sei - Dream Tag Match (Japan)"},
["274719f5"] = {name = "Kurupara! (Japan) (Rev 1)"},
["09a94f00"] = {name = "Kuttsuke Su (World) (Ja) (WonderWitch) (Unl)"},
["da4479bf"] = {name = "Last Alive (Japan)"},
["a1818b41"] = {name = "Lolita Queen (World) (WonderWitch) (Unl)"},
["ce84799e"] = {name = "Mahha de Tsuugaku!! (World) (WonderWitch) (Unl)"},
["1b6f5f30"] = {name = "Makai Toushi Sa-Ga (Japan)"},
["f366172e"] = {name = "mama Mitte (Japan) (Program)"},
["867a8a3f"] = {name = "mama Mitte (Japan) (Rev D) (Program)"},
["858c53bb"] = {name = "Mawase Mawase WonderSwan Mawase (World) (WonderWitch) (Unl)"},
["8c0c49d4"] = {name = "Maze Maze (World) (WonderWitch) (Unl)"},
["9f6e3f8d"] = {name = "Meitantei Conan - Yuugure no Oujo (Japan)"},
["8e123373"] = {name = "Memories Off - Festa (Japan)"},
["d75effc2"] = {name = "Mikeneko Holmes - Ghost Panic (Japan)"},
["acec2b13"] = {name = "Monmon Gunner (World) (Ja) (WonderWitch) (Unl)"},
["16566668"] = {name = "Moverang (World) (WonderWitch) (Unl)"},
["5555d95c"] = {name = "Mr. Driller (Japan)"},
["196fd1ce"] = {name = "Multi-BoaRD (World) (WonderWitch) (Unl)"},
["8ce4652f"] = {name = "Namco Super Wars (Japan)"},
["23f6215d"] = {name = "Nametry (World) (WonderWitch) (Unl)"},
["71556e6a"] = {name = "Naruto - Konoha Ninpouchou (Japan)"},
["f79be3b5"] = {name = "NAVI GET 400 Million (Japan) (Version 1.0) (Program)"},
["4c6cbdb2"] = {name = "NAVI GET 400 Million (Japan) (Version 3.0) (Program)"},
["0a072698"] = {name = "NAVI GET 400 Million (Japan) (Version 2.1) (Program)"},
["83512340"] = {name = "NAVI GET 400 Million (Japan) (Version 9) (Program)"},
["bde8e20d"] = {name = "Neko no Kurubushi (World) (WonderWitch) (Unl)"},
["3f743f54"] = {name = "Nijiiro Dandodan (World) (Ja) (WonderWitch) (Unl)"},
["420ff6ce"] = {name = "Octopus Mahjong, The (World) (Ja) (v0.92) (WonderWitch) (Unl)"},
["15ffe8bd"] = {name = "One Dazen Won! (World) (v0.02) (Proto) (WonderWitch) (Unl)"},
["01274d5a"] = {name = "Ougon (World) (WonderWitch) (Unl)"},
["431f49d6"] = {name = "Panic Wonder (World) (WonderWitch) (Unl)"},
["b72065f8"] = {name = "Pepperas! (World) (v0.40) (Proto) (WonderWitch) (Unl)"},
["2f9bae0a"] = {name = "Petit Balls (World) (WonderWitch) (Unl)"},
["9c0dfcc5"] = {name = "Petit PazzLe (World) (Ja) (WonderWitch) (Unl)"},
["5d6a60e0"] = {name = "Petit Shooo (World) (WonderWitch) (Unl)"},
["bb00fd33"] = {name = "Petit SounD (World) (Ja) (WonderWitch) (Program)"},
["588cb4e5"] = {name = "Pink Passer (World) (Ja) (v0.01) (Proto) (WonderWitch) (Unl)"},
["85dafad7"] = {name = "Pittari! (World) (Ja) (WonderWitch) (Unl)"},
["9fdc9413"] = {name = "Pladel 2 (World) (WonderWitch) (Unl)"},
["2b61bb2b"] = {name = "Pocket no Naka no Doraemon (Japan)"},
["727116fc"] = {name = "Poker (World) (Ja) (WonderWitch) (Unl)"},
["a109567e"] = {name = "Putipati (World) (v1.12) (WonderWitch) (Unl)"},
["f4b6eef1"] = {name = "Putipati (World) (v1.11) (WonderWitch) (WWGP2002) (Unl)"},
["fe4ff701"] = {name = "Raku Jongg (Japan)"},
["e912a376"] = {name = "Rave Hunter (World) (WonderWitch) (Unl)"},
["525e367b"] = {name = "Reversi (World) (Ja) (WonderWitch) (Unl)"},
["60706555"] = {name = "Rhyme Rider Kerorican (Japan)"},
["78a07676"] = {name = "Rhythmin (World) (Ja) (WonderWitch) (Unl)"},
["2460b45a"] = {name = "Riviera - Yakusoku no Chi Riviera (Japan)"},
["62cb398b"] = {name = "Riviera - Yakusoku no Chi Riviera (Japan) (Rev 1)"},
["1f10ca75"] = {name = "Rockman EXE - N1 Battle (Japan) (Rev 1)"},
["658c4b98"] = {name = "Rockman EXE WS (Japan)"},
["9c98d97d"] = {name = "Romancing Sa-Ga (Japan)"},
["15c4552e"] = {name = "RUN=DIM - Return to Earth (Japan)"},
["6e8a792d"] = {name = "Saint Seiya - Ougon Densetsu Hen - Perfect Edition (Japan)"},
["50db2635"] = {name = "Samegame for WSC (World) (WonderWitch) (Unl)"},
["c59bf216"] = {name = "Samoner (World) (Ja) (WonderWitch) (Unl)"},
["f32db2f1"] = {name = "Saorin Puzzle (World) (Demo) (WonderWitch) (Unl)"},
["4c85fcaa"] = {name = "Satori - WonderSwan Remix (World) (WonderWitch) (Unl)"},
["f0acda5c"] = {name = "SD Gundam - Operation U.C. (Japan)"},
["c60e5162"] = {name = "SD Gundam Eiyuu Den - Kishi Densetsu (Japan)"},
["18ecffb8"] = {name = "SD Gundam Eiyuu Den - Musha Densetsu (Japan)"},
["4d21a347"] = {name = "SD Gundam G Generation - Gather Beat 2 (Japan)"},
["6aca1f04"] = {name = "SD Gundam G Generation - Mono-Eye Gundams (Japan)"},
["a3ecc9ac"] = {name = "SD Gundam G Generation - Mono-Eye Gundams (Japan) (Rev 2)"},
["9f35d00f"] = {name = "Senkaiden Ni - TV Animation Senkaiden Houshin Engi Yori (Japan)"},
["6c029674"] = {name = "Shaman King - Asu e no Ishi (Japan)"},
["34908cb4"] = {name = "Shaman King - Asu e no Ishi (Japan) (Rev 1)"},
["e58ef5cb"] = {name = "Shokaku 80186 (World) (WonderWitch) (Unl)"},
["2aeed79a"] = {name = "SLG Kyara Idou Sanpuru (World) (Demo) (WonderWitch) (Unl)"},
["9ef5c2c9"] = {name = "Solfege (World) (WonderWitch) (Unl)"},
["0e467d97"] = {name = "Sorobang (Japan) (Rev 1)"},
["138d1018"] = {name = "Star Hearts - Hoshi to Daichi no Shisha (Japan)"},
["9874e9a2"] = {name = "Star Hearts - Hoshi to Daichi no Shisha - Taikenban (Japan) (Not For Sale)"},
["0ce861d4"] = {name = "Star Ochi (World) (WonderWitch) (Unl)"},
["b7e179d9"] = {name = "Starlight Waltz (World) (Proto) (WonderWitch) (Unl)"},
["6918c824"] = {name = "Super Robot Taisen Compact 3 (Japan) (Rev 5)"},
["188ca644"] = {name = "Super Robot Taisen Compact 3 (Japan) (Rev 6)"},
["16e0d929"] = {name = "Super Robot Taisen Compact for WonderSwan Color (Japan)"},
["9f98d0c2"] = {name = "Surround (World) (Proto) (WonderWitch) (Unl)"},
["ec2e8b11"] = {name = "Tank Move Color (World) (WonderWitch) (Unl)"},
["9bd8f08c"] = {name = "Terrors 2 (Japan)"},
["7b0caea9"] = {name = "Tetris (Japan)"},
["bea730c6"] = {name = "Tonde Stone (World) (WonderWitch) (Unl)"},
["47659b2c"] = {name = "Tonpuusou (Japan)"},
["5793bdda"] = {name = "Uchuu Senkan Yamato (Japan)"},
["de2208ab"] = {name = "Ultraman - Hikari no Kuni no Shisha (Japan)"},
["776d961c"] = {name = "UnderBabel (Main Data) (World) (Ja) (WonderWitch) (Unl)"},
["f0b5886c"] = {name = "UnderBabel (Supporting Data) (World) (Ja) (WonderWitch) (Unl)"},
["d008c8cc"] = {name = "Visual Sequencer MUCOS (World) (Ja) (WonderWitch) (Program) (Unl)"},
["bd2a1d58"] = {name = "War Cup (World) (Ja) (Proto) (WonderWitch) (Unl)"},
["fd6767c9"] = {name = "Well-being (World) (WonderWitch) (Unl)"},
["d9401f0a"] = {name = "Wild Card (Japan)"},
["4180ab58"] = {name = "Witch Typing (World) (Ja) (WonderWitch) (Unl)"},
["8b743abd"] = {name = "Witches! (World) (WonderWitch) (Unl)"},
["e14e9d36"] = {name = "With You - Mitsumete Itai (Japan)"},
["15e55706"] = {name = "Wizardry Scenario 1 - Proving Grounds of the Mad Overlord (Japan)"},
["12f10b27"] = {name = "Wonder Classic (Japan)"},
["d993f2d0"] = {name = "Wonder Racer (World) (WonderWitch) (Unl)"},
["64a358f5"] = {name = "WonderCommand (World) (WonderWitch) (Program)"},
["66b617d5"] = {name = "X - Card of Fate (Japan)"},
["25e2ba75"] = {name = "XI Little (Japan)"},
["48f14c43"] = {name = "Yokeru Kamo (World) (v1.1) (WonderWitch) (Unl)"},
["857c1f7a"] = {name = "Yokeru Kamo (World) (v1.0) (WonderWitch) (WWGP2002)"},
}