return
{
["4342db9d"] = {name = "11 Hap Gam-Boy (Korea) (Unl)"},
["ba5ec0e3"] = {name = "128 Hap (Korea) (Unl)"},
["1b3e032e"] = {name = "2 Hap in 1 - Moai-ui Bomul + David II (Korea) (Unl)"},
["f0f35c22"] = {name = "20 em 1 (Brazil)"},
["98af0236"] = {name = "3 in 1 - The Best Game Collection (A) (Korea) (En) (Unl)"},
["6ebfe1c3"] = {name = "3 in 1 - The Best Game Collection (B) (Korea) (En) (Unl)"},
["81a36a4f"] = {name = "3 in 1 - The Best Game Collection (C) (Korea) (En) (Unl)"},
["8d2d695d"] = {name = "3 in 1 - The Best Game Collection (D) (Korea) (En) (Unl)"},
["82c09b57"] = {name = "3 in 1 - The Best Game Collection (E) (Korea) (En) (Unl)"},
["4088eeb4"] = {name = "3 in 1 - The Best Game Collection (F) (Korea) (En) (Unl)"},
["56dcb2d4"] = {name = "3D Gunner (USA) (Beta)"},
["a67f2a5c"] = {name = "4 PAK All Action (Australia) (Unl)"},
["fba94148"] = {name = "8 in 1 - The Best Game Collection (A) (Korea) (En) (Unl)"},
["8333c86e"] = {name = "8 in 1 - The Best Game Collection (B) (Korea) (En) (Unl)"},
["00e9809f"] = {name = "8 in 1 - The Best Game Collection (C) (Korea) (En) (Unl)"},
["060d6a7c"] = {name = "94 Super World Cup Soccer (Korea) (Unl)"},
["6fe448a5"] = {name = "94-Nen Super Basketball (Taiwan) (En) (Unl)"},
["0eb430ff"] = {name = "A-Team Music, The (Unknown) (Proto) (1992-11-09) (Sound Data)"},
["887d9f6b"] = {name = "Ace of Aces (Europe, Brazil) (En)"},
["b3440203"] = {name = "Acerte o Alvo (Brazil) (Mega Drive 4)"},
["d0263024"] = {name = "Action Boy (Taiwan) (En) (Unl)"},
["e2d765ad"] = {name = "Action Fighter (Japan, Europe) (En) (Beta)"},
["3658f3e0"] = {name = "Action Fighter (USA, Europe, Brazil) (En) (Rev 1)"},
["d91b340d"] = {name = "Action Fighter (Japan, Europe) (En)"},
["8418f438"] = {name = "Action Fighter (Taiwan) (Unl)"},
["72420f38"] = {name = "Addams Family, The (Europe)"},
["ecf491cf"] = {name = "Aerial Assault (Europe, Brazil) (En)"},
["15576613"] = {name = "Aerial Assault (USA)"},
["6630e5fd"] = {name = "Aerial Assault (Taiwan) (En) (Unl)"},
["1c951f8e"] = {name = "After Burner (World)"},
["4f1be9fa"] = {name = "Agigongnyong Dooly (Korea) (Unl)"},
["8b43d21d"] = {name = "Air Rescue (Europe, Brazil) (En)"},
["c8718d40"] = {name = "Aladdin (Europe, Brazil) (En)"},
["d8c4165b"] = {name = "Aleste (Japan)"},
["013c0a94"] = {name = "Alex Kidd - High-Tech World (USA, Europe, Brazil) (En)"},
["2d7fabb2"] = {name = "Alex Kidd - High-Tech World (USA, Europe, Brazil) (En) (Beta)"},
["c13896d5"] = {name = "Alex Kidd - The Lost Stars (World)"},
["17a40e29"] = {name = "Alex Kidd in Miracle World (USA, Europe)"},
["aed9aac4"] = {name = "Alex Kidd in Miracle World (USA, Europe, Brazil) (En) (Rev 1)"},
["6f5f3daa"] = {name = "Alex Kidd in Miracle World (World) (Ja) (Sega Ages)"},
["50a8e8a7"] = {name = "Alex Kidd in Miracle World (World) (Sega Ages)"},
["7de172ff"] = {name = "Alex Kidd in Miracle World 2 (World) (Unl)"},
["d2417ed7"] = {name = "Alex Kidd in Shinobi World (USA, Europe, Brazil) (En)"},
["08c9ec91"] = {name = "Alex Kidd no Miracle World (Japan)"},
["6f8e46cf"] = {name = "Alex Kido (Taiwan) (En) (Unl)"},
["82038ad4"] = {name = "Alf (USA)"},
["08bf3de3"] = {name = "Alibaba and 40 Thieves (Korea) (En) (Unl)"},
["b618b144"] = {name = "Alien 3 (Europe, Brazil) (En)"},
["7f30f793"] = {name = "Alien Storm (Europe, Brazil) (En)"},
["5cbfe997"] = {name = "Alien Syndrome (USA, Europe, Brazil) (En)"},
["c148868c"] = {name = "Alien Syndrome (USA, Europe, Brazil) (En) (Beta)"},
["4cc11df9"] = {name = "Alien Syndrome (Japan)"},
["5e4b454e"] = {name = "Alocos (Taiwan) (En) (Unl)"},
["bba2fe98"] = {name = "Altered Beast (USA, Europe, Brazil) (En)"},
["7b27202f"] = {name = "American Baseball (Europe, Brazil) (En)"},
["3727d8b2"] = {name = "American Pro Football (Europe)"},
["f499034d"] = {name = "Andre Agassi Tennis (Europe, Brazil) (En)"},
["fff63b0b"] = {name = "Anmitsu Hime (Japan)"},
["e4163163"] = {name = "Arcade Smash Hits (Europe)"},
["bae75805"] = {name = "Argos no Juujiken (Japan)"},
["f4b3a7bd"] = {name = "Ariel - The Little Mermaid (Brazil) (En)"},
["ae705699"] = {name = "Ashura (Japan)"},
["861b6e79"] = {name = "Assault City (USA, Europe, Brazil) (En) (Light Phaser)"},
["0bd8da96"] = {name = "Assault City (Europe) (Joypad)"},
["147e02fa"] = {name = "Asterix (Europe, Brazil) (En,Fr)"},
["8c9d5be8"] = {name = "Asterix (Europe, Brazil) (En,Fr) (Rev 1)"},
["f9b7d26b"] = {name = "Asterix and the Great Rescue (Europe, Brazil) (En,Fr,De,Es,It)"},
["def9b14e"] = {name = "Asterix and the Secret Mission (Europe, Brazil) (En,Fr,De)"},
["fb163003"] = {name = "Astro Adventure (Taiwan) (En) (Unl)"},
["c795182d"] = {name = "Astro Flash (Japan)"},
["299cbb74"] = {name = "Astro Warrior (Japan, USA, Brazil) (En)"},
["69efd483"] = {name = "Astro Warrior & Pit Pot (Europe)"},
["3da7f1ce"] = {name = "Astro Warrior & Pit Pot (Europe) (Sample)"},
["daf4ac7b"] = {name = "Astro Warrior & Pit Pot (Brazil) (En) (2011 Master System Evolution)"},
["e1714a88"] = {name = "Aventuras da TV Colosso, As (Brazil)"},
["e890331d"] = {name = "Ayrton Senna's Super Monaco GP II (Europe, Brazil) (En)"},
["ff614eb3"] = {name = "Aztec Adventure (World)"},
["7ca37320"] = {name = "Aztel Adventure (Taiwan) (En) (Unl)"},
["e5ff50d8"] = {name = "Back to the Future Part II (Europe, Brazil) (En)"},
["2d48c1d3"] = {name = "Back to the Future Part III (Europe)"},
["35d84dc2"] = {name = "Baku Baku (Brazil) (En)"},
["655fb1f4"] = {name = "Bank Panic (Europe, Brazil) (En)"},
["0df8597f"] = {name = "Basketball Nightmare (Europe, Brazil) (En)"},
["e5b3573e"] = {name = "Basketball Nightmare (Europe, Brazil) (En) (Beta 2)"},
["4e3ebb55"] = {name = "Basketball Nightmare (Europe, Brazil) (En) (Beta 1)"},
["b154ec38"] = {name = "Batman Returns (Europe, Brazil) (En)"},
["c19430ce"] = {name = "Battle Out Run (Europe, Brazil) (En)"},
["fae0ade7"] = {name = "Battle Wings (World) (Beta) (1988-09-07)"},
["1cbb7bf1"] = {name = "Battlemaniacs (Brazil) (En)"},
["da3a2f57"] = {name = "Black Belt (USA, Europe, Brazil) (En)"},
["98f64975"] = {name = "Black Belt (Taiwan) (En) (Unl)"},
["58d5fc48"] = {name = "Blade Eagle (World) (Beta)"},
["8ecd201c"] = {name = "Blade Eagle 3-D (World)"},
["f9dbb533"] = {name = "BMX Trial - Alex Kidd (Japan)"},
["25eb9f80"] = {name = "Bobble Bobble (Korea) (En) (Unl)"},
["b2885ba0"] = {name = "Bolas e Cores (Brazil) (Mega Drive 4)"},
["8351496a"] = {name = "Bolhas (Brazil) (Mega Drive 4)"},
["c8e38178"] = {name = "Bombeiros (Brazil) (Mega Drive 4)"},
["3084cf11"] = {name = "Bomber Raid (World)"},
["caea8002"] = {name = "Bonanza Bros. (Europe, Brazil) (En)"},
["b3768a7a"] = {name = "Bonkers Wax Up! (Brazil) (En)"},
["1b10a951"] = {name = "Bram Stoker's Dracula (Europe)"},
["e843ba7e"] = {name = "Bubble Bobble (Europe, Brazil) (En)"},
["b948752e"] = {name = "Bubble Bobble (Taiwan) (En) (Unl)"},
["b0fc4577"] = {name = "Buggy Run (Europe, Brazil) (En)"},
["0918fba0"] = {name = "C_So! (Korea) (Unl)"},
["ac6009a7"] = {name = "California Games (USA, Europe, Brazil) (En)"},
["c0e25d62"] = {name = "California Games II (Europe)"},
["b81f6fa5"] = {name = "Captain Silver (USA)"},
["2532a7cd"] = {name = "Captain Silver (USA) (Beta)"},
["a4852757"] = {name = "Captain Silver (Japan, Europe, Brazil) (En)"},
["3cff6e80"] = {name = "Casino Games (USA, Europe)"},
["31ffd7c3"] = {name = "Castelo Ra-Tim-Bum (Brazil)"},
["ee0f98ca"] = {name = "Castle of Illusion Starring Mickey Mouse (USA, Europe, Brazil) (En) (Demo)"},
["953f42e1"] = {name = "Castle of Illusion Starring Mickey Mouse (USA, Europe, Brazil) (En) (Rev 1)"},
["b9db4282"] = {name = "Castle of Illusion Starring Mickey Mouse (USA, Europe, Brazil) (En)"},
["c386e835"] = {name = "Cava-Cava (Brazil) (Mega Drive 4)"},
["23163a12"] = {name = "Champions of Europe (Europe, Brazil) (En)"},
["7e5839a0"] = {name = "Championship Hockey (Europe)"},
["492c7c6e"] = {name = "Chapolim x Dracula - Um Duelo Assustador (Brazil)"},
["46340c41"] = {name = "Cheese Cat-astrophe Starring Speedy Gonzales (Europe, Brazil) (En,Fr,De,Es)"},
["4a21c15f"] = {name = "Choplifter (USA, Europe, Brazil) (En)"},
["fd981232"] = {name = "Choplifter (USA, Europe, Brazil) (En) (Beta)"},
["16ec3575"] = {name = "Choplifter (Japan) (Proto)"},
["55f929ce"] = {name = "Choplifter (Taiwan) (En) (Unl)"},
["e421e466"] = {name = "Chouon Senshi Borgman (Japan)"},
["86f49ae9"] = {name = "Chouon Senshi Borgman (Japan) (Beta)"},
["dd0e2927"] = {name = "Chuck Rock (Europe, Brazil) (En)"},
["87783c04"] = {name = "Chuck Rock II - Son of Chuck (Brazil) (En)"},
["c30e690a"] = {name = "Chuck Rock II - Son of Chuck (Europe)"},
["8fb75994"] = {name = "Circuit, The (Japan)"},
["e7f62e6d"] = {name = "Cloud Master (USA, Europe, Brazil) (En)"},
["7253c3ec"] = {name = "Color & Switch Test (Japan) (En) (Proto)"},
["b06403e0"] = {name = "Color & Switch Test (Brazil) (En) (Rev 1)"},
["3fb40043"] = {name = "Columns (USA, Europe, Brazil) (En) (Beta)"},
["665fda92"] = {name = "Columns (USA, Europe, Brazil) (En)"},
["84ad5ae4"] = {name = "Comical Machine Gun Joe (Taiwan) (Unl)"},
["9d549e08"] = {name = "Comical Machine Gun Joe (Japan)"},
["643f6bfc"] = {name = "Comical Machine Gun Joe (Korea) (Unl)"},
["1e1b9f59"] = {name = "Con-Dori (Korea) (Unl)"},
["13ac9023"] = {name = "Cool Spot (Europe)"},
["29822980"] = {name = "Cosmic Spacehead (Europe) (En,Fr,De,Es)"},
["d260006a"] = {name = "Creature Capture (Brazil) (Mega Drive 4)"},
["dac00a3a"] = {name = "Cyber Shinobi, The (Europe, Brazil) (En) (Beta)"},
["1350e4f8"] = {name = "Cyber Shinobi, The (Europe, Brazil) (En)"},
["ad9ff469"] = {name = "Cyber Shinobi, The (Taiwan) (En) (Unl)"},
["908e7524"] = {name = "Cyborg Hunter (USA, Europe, Brazil) (En)"},
["691211a1"] = {name = "Cyborg Hunter (USA, Europe, Brazil) (En) (Beta) (1988-09-12)"},
["77efe84a"] = {name = "Cyborg Z (Korea) (Unl)"},
["71abef27"] = {name = "Daffy Duck in Hollywood (Europe, Brazil) (En,Fr,De,Es,It)"},
["89b79e77"] = {name = "Dallyeora Pigu-Wang (Korea) (Unl)"},
["ae4a28d7"] = {name = "Danan - The Jungle Fighter (Europe, Brazil) (En)"},
["e2f7193e"] = {name = "Dead Angle (USA, Europe, Brazil) (En)"},
["f9271c3d"] = {name = "Dead Angle (USA, Europe, Brazil) (En) (Beta)"},
["42fc3a6e"] = {name = "Deep Duck Trouble Starring Donald Duck (Europe, Brazil) (En)"},
["b137007a"] = {name = "Desert Speedtrap Starring Road Runner and Wile E. Coyote (Europe, Brazil) (En,Fr,De,Es,It)"},
["6c1433f9"] = {name = "Desert Strike (Europe) (En,Fr,De,Es)"},
["f6fab48d"] = {name = "Dick Tracy (USA, Europe, Brazil) (En)"},
["ea5c3a6f"] = {name = "DINOBASHER - Starring Bignose the Caveman (Europe) (Proto)"},
["32f4b791"] = {name = "Dinosaur Dooley, The (Korea) (En) (Unl)"},
["56bd2455"] = {name = "Doki Doki Penguin Land - Uchuu Daibouken (Japan) (Beta)"},
["2bcdb8fa"] = {name = "Doki Doki Penguin Land - Uchuu Daibouken (Japan)"},
["8b6cd69c"] = {name = "Domino (Brazil) (Mega Drive 4)"},
["a55d89f3"] = {name = "Double Dragon (World)"},
["f4f848c2"] = {name = "Double Dragon (Taiwan) (En) (Unl)"},
["8370f6cd"] = {name = "Double Hawk (Europe)"},
["f76d5cee"] = {name = "Double Hawk (Europe) (Beta)"},
["52b83072"] = {name = "Double Target - Cynthia no Nemuri (Japan)"},
["ab5d74a8"] = {name = "Doze Trabalhos de Jongo, Os (Brazil) (Mega Drive 4)"},
["16537865"] = {name = "Dr. HELLO (Korea) (En) (Unl)"},
["6c696221"] = {name = "Dr. Robotnik's Mean Bean Machine (Europe, Brazil) (En)"},
["c88a5064"] = {name = "Dragon - The Bruce Lee Story (Europe)"},
["9549fce4"] = {name = "Dragon Crystal (Europe, Brazil) (En)"},
["07306947"] = {name = "Dynamite Duke (Europe, Brazil) (En)"},
["0e1cc1e0"] = {name = "Dynamite Dux (Europe, Brazil) (En)"},
["4e59175e"] = {name = "Dynamite Dux (Europe, Brazil) (En) (Beta)"},
["7db5b0fa"] = {name = "Dynamite Headdy (Brazil) (En)"},
["c10fce39"] = {name = "E-SWAT (USA, Europe, Brazil) (En) (Rev A)"},
["fd91cc7e"] = {name = "E-SWAT (USA, Europe, Brazil) (En) (Beta 3)"},
["f7ca9801"] = {name = "E-SWAT (USA, Europe, Brazil) (En) (Beta 2)"},
["c4bb1676"] = {name = "E-SWAT (USA, Europe, Brazil) (En)"},
["4f20694a"] = {name = "E-SWAT (USA, Europe, Brazil) (En) (Beta 1)"},
["96e16fe4"] = {name = "E-SWAT (Taiwan) (En) (Unl)"},
["dd74bcf1"] = {name = "E.I. - Exa Innova (Korea) (En) (Unl)"},
["f06f2ccb"] = {name = "Eagles 5 (Korea) (Unl)"},
["c4d5efc5"] = {name = "Earthworm Jim (Brazil) (En)"},
["7c28703a"] = {name = "Ecco - The Tides of Time (Brazil)"},
["6687fab9"] = {name = "Ecco The Dolphin (Europe, Brazil) (En)"},
["00e73541"] = {name = "Enduro Racer (USA, Europe, Brazil) (En)"},
["5d5c50b3"] = {name = "Enduro Racer (Japan)"},
["8813514b"] = {name = "Excellent Dizzy Collection, The (Europe) (En,Fr,De,Es,It) (Proto)"},
["06965ed9"] = {name = "F-1 Spirit - The Way to Formula-1 (Korea) (En) (Unl)"},
["eaebf323"] = {name = "F-16 Fighter (USA, Europe, Brazil) (En)"},
["7ce06fce"] = {name = "F-16 Fighting Falcon (Japan)"},
["c4c53226"] = {name = "F-16 Fighting Falcon (Taiwan) (Unl)"},
["184c23b7"] = {name = "F-16 Fighting Falcon (USA)"},
["ec788661"] = {name = "F1 (Europe, Brazil) (En)"},
["17ab6883"] = {name = "FA Tetris (Korea) (Unl)"},
["88c0207f"] = {name = "Fabrica de Chocolate (Brazil) (Mega Drive 4)"},
["7abc70e9"] = {name = "Family Games (Japan)"},
["b9664ae1"] = {name = "Fantastic Dizzy (Europe) (En,Fr,De,Es,It)"},
["0ffbcaa3"] = {name = "Fantasy Zone (Japan)"},
["f46264fe"] = {name = "Fantasy Zone (World) (Beta)"},
["5fd48352"] = {name = "Fantasy Zone (Taiwan) (Unl)"},
["65d7e4e0"] = {name = "Fantasy Zone (World) (Rev 1)"},
["d29889ad"] = {name = "Fantasy Zone - The Maze (USA, Europe, Brazil) (En)"},
["b8b141f9"] = {name = "Fantasy Zone II (USA, Europe, Brazil) (En)"},
["c722fb42"] = {name = "Fantasy Zone II - Opa-Opa no Namida (Japan)"},
["1df0fc90"] = {name = "Feiche Zhengba Zhan (Taiwan) (En) (Unl)"},
["bf6c2e37"] = {name = "Ferias Frustradas do Pica Pau (Brazil)"},
["9bb3b5f9"] = {name = "FIFA International Soccer (Brazil) (En,Es,Pt)"},
["3ebb7457"] = {name = "Final Bubble Bobble (Japan)"},
["f6ad7b1d"] = {name = "Fire & Forget II (Europe)"},
["8b24a640"] = {name = "Fire & Ice (Brazil) (En)"},
["be31d63f"] = {name = "Flash, The (Europe, Brazil) (En)"},
["61e8806f"] = {name = "Flashpoint (Korea) (Unl)"},
["ca5c78a5"] = {name = "Flintstones, The (Europe, Brazil) (En)"},
["38c53916"] = {name = "Forgotten Worlds (Europe, Brazil) (En)"},
["44136a72"] = {name = "Forgotten Worlds (Taiwan) (En) (Unl)"},
["e6795c53"] = {name = "Fushigi no Oshiro Pit Pot (Japan)"},
["73c76d15"] = {name = "Fushigi no Oshiro Pit Pot (Japan) (Beta)"},
["05cdc24e"] = {name = "G-LOC - Air Battle (Europe, Brazil) (En)"},
["8b40f6bf"] = {name = "Gaegujangi Ggachi (Korea) (Unl)"},
["3ec5e627"] = {name = "Gain Ground (Europe, Brazil) (En)"},
["d40d03c7"] = {name = "Gain Ground (Europe, Brazil) (En) (Beta)"},
["a6fa42d0"] = {name = "Galactic Protector (Japan)"},
["577ec227"] = {name = "Galaxian (Korea) (Unl)"},
["a4ac35d8"] = {name = "Galaxy Force (Europe, Brazil) (En)"},
["6c827520"] = {name = "Galaxy Force (USA)"},
["1890f407"] = {name = "Game Box Serie Esportes Radicais (Brazil) (En)"},
["38b3a72f"] = {name = "Game Chongjiphap 200 (Korea) (Unl)"},
["9afab511"] = {name = "Game de Check! Koutsuu Anzen (Japan) (Proto)"},
["380d7400"] = {name = "Game Mo-eumjip 188 Hap (Korea) (v1.0) (Unl)"},
["c76601e0"] = {name = "Game Mo-eumjip 188 Hap (Korea) (v1.1) (Unl)"},
["ad522efd"] = {name = "Gangcheol RoboCop (Korea) (En) (Unl)"},
["5fc74d2a"] = {name = "Gangster Town (USA, Europe, Brazil) (En)"},
["d9190956"] = {name = "Gauntlet (Europe, Brazil) (En)"},
["a64898ce"] = {name = "George Foreman's KO Boxing (Europe, Brazil) (En)"},
["956c416b"] = {name = "Geraldinho (Brazil) (En)"},
["f1f8ff2d"] = {name = "Ghost House (USA, Europe, Brazil) (En)"},
["c0f3ce7e"] = {name = "Ghost House (Japan)"},
["c3e7c1ed"] = {name = "Ghost House (USA, Europe, Brazil) (En) (Beta)"},
["1ddc3059"] = {name = "Ghostbusters (USA, Europe, Brazil) (En)"},
["38418b1c"] = {name = "Ghouls'n Ghosts (USA, Europe, Brazil) (En) (Demo)"},
["7a92eba6"] = {name = "Ghouls'n Ghosts (USA, Europe, Brazil) (En)"},
["b746a6f5"] = {name = "Global Defense (USA, Europe, Brazil) (En)"},
["91a0fc4e"] = {name = "Global Defense (USA, Europe, Brazil) (En) (Beta)"},
["b67ceb76"] = {name = "Global Gladiators (Europe, Brazil) (En)"},
["a249fa9d"] = {name = "Gokuaku Doumei Dump Matsumoto (Japan)"},
["c08132fb"] = {name = "Golden Axe (USA, Europe, Brazil) (En)"},
["a471f450"] = {name = "Golden Axe (USA, Europe, Brazil) (En) (Demo)"},
["c7ded988"] = {name = "Golden Axe Warrior (USA, Europe, Brazil) (En)"},
["5dabfdc3"] = {name = "Golfamania (Europe) (Beta)"},
["48651325"] = {name = "Golfamania (Europe, Brazil) (En)"},
["a51376fe"] = {name = "Golvellius - Valley of Doom (USA, Europe, Brazil) (En)"},
["ec2da554"] = {name = "GP Rider (Europe, Brazil) (En)"},
["10ed6b57"] = {name = "Great Baseball (USA, Europe)"},
["89e98a7c"] = {name = "Great Baseball (Japan)"},
["2ac001eb"] = {name = "Great Basketball (World)"},
["2055825f"] = {name = "Great Football (World)"},
["5def1bf5"] = {name = "Great Golf (Korea) (En) (Unl)"},
["98e4ae4a"] = {name = "Great Golf (World)"},
["4847bc91"] = {name = "Great Golf (World) (Beta)"},
["6586bd1f"] = {name = "Great Golf (Japan)"},
["946b8c4a"] = {name = "Great Ice Hockey (Japan, USA) (En)"},
["2d7fd7ef"] = {name = "Great Soccer (Japan)"},
["0ed170c9"] = {name = "Great Soccer (Europe)"},
["84665648"] = {name = "Great Soccer (Taiwan) (Unl)"},
["95cbf3dd"] = {name = "Great Tennis (Japan)"},
["6819b0c0"] = {name = "Great Volleyball (Japan)"},
["8d43ea95"] = {name = "Great Volleyball (USA, Europe, Brazil) (En)"},
["3af7ccad"] = {name = "Gun.Smoke (Korea) (En) (Unl)"},
["b9fdf6d9"] = {name = "Haja no Fuuin (Japan)"},
["071b045e"] = {name = "Hang On (Europe)"},
["5c01adf9"] = {name = "Hang On (Japan)"},
["649f29e8"] = {name = "Hang On (Europe) (Beta)"},
["1c5059f0"] = {name = "Hang On & Astro Warrior (USA)"},
["a120b77f"] = {name = "Hang On & Safari Hunt (USA) (Beta)"},
["e167a561"] = {name = "Hang On & Safari Hunt (USA)"},
["fdab876a"] = {name = "Heavyweight Champ (Europe, Brazil) (En)"},
["cde13ffb"] = {name = "Heroes of the Lance (Europe, Brazil) (En)"},
["9611bebd"] = {name = "Heroes of the Lance (Europe, Brazil) (En) (Beta)"},
["9eb1aa4f"] = {name = "High School! Kimengumi (Japan)"},
["c4ab363d"] = {name = "Hokuto no Ken (Taiwan) (Unl)"},
["24f5fe8c"] = {name = "Hokuto no Ken (Japan)"},
["c9dbf936"] = {name = "Home Alone (Europe)"},
["8040b2fa"] = {name = "Hong Kil Dong (Korea) (Unl)"},
["9ced34a7"] = {name = "Hook (Europe) (Proto)"},
["955a009e"] = {name = "Hoshi wo Sagashite... (Japan)"},
["e4b7c56a"] = {name = "Hwarang-ui Geom (Korea) (Unl)"},
["71c4ca8f"] = {name = "Impossible Mission (Europe, Brazil) (En) (Beta)"},
["64d6af3b"] = {name = "Impossible Mission (Europe, Brazil) (En)"},
["b4584dde"] = {name = "Incredible Crash Dummies, The (Europe, Brazil) (En)"},
["be9a7071"] = {name = "Incredible Hulk, The (Europe, Brazil) (En)"},
["acec894d"] = {name = "Indiana Jones and the Last Crusade (USA) (Proto)"},
["8aeb574b"] = {name = "Indiana Jones and the Last Crusade (Europe, Brazil) (En)"},
["cfb4bd7b"] = {name = "James 'Buster' Douglas Knockout Boxing (USA) (Sample)"},
["6a664405"] = {name = "James 'Buster' Douglas Knockout Boxing (USA)"},
["8feff688"] = {name = "James Bond 007 - The Duel (Brazil) (En)"},
["8d23587f"] = {name = "James Bond 007 - The Duel (Europe)"},
["102d5fea"] = {name = "James Pond 2 - Codename RoboCod (Europe, Brazil) (En)"},
["18fb98a3"] = {name = "Jang Pung 3 (Korea) (Unl)"},
["929222c4"] = {name = "Jang Pung II (Korea) (Unl)"},
["192949d5"] = {name = "Janggun-ui Adeul (Korea) (Unl)"},
["0a9089e5"] = {name = "Joe Montana Football (USA, Europe, Brazil) (En)"},
["45c50294"] = {name = "Jogos de Verao II (Brazil) (En)"},
["695a9a15"] = {name = "Jungle Book, The (Europe, Brazil) (En)"},
["0667ed9f"] = {name = "Jurassic Park (Europe, Brazil) (En)"},
["516ed32e"] = {name = "Kenseiden (USA, Europe, Brazil) (En)"},
["05ea5353"] = {name = "Kenseiden (Japan)"},
["0ae470e5"] = {name = "King & Balloon (Korea) (En) (Unl)"},
["f8d33bc4"] = {name = "King's Quest - Quest for the Crown (USA)"},
["b7fe0a9d"] = {name = "King's Quest - Quest for the Crown (USA) (Beta 2)"},
["fd27bef1"] = {name = "King's Quest - Quest for the Crown (USA) (Beta 1)"},
["2b435fd6"] = {name = "KLAX (Europe)"},
["f89af3cc"] = {name = "Knightmare II - The Maze of Galious (Korea) (Unl)"},
["64a585eb"] = {name = "Krusty's Fun House (Europe, Brazil) (En)"},
["d11d32e4"] = {name = "Kujaku Ou (Japan)"},
["1e949d1f"] = {name = "Kung Fu Kid (USA, Europe, Brazil) (En)"},
["4762e022"] = {name = "Kung Fu Kid (Taiwan) (En) (Unl)"},
["24e97200"] = {name = "Land of Illusion Starring Mickey Mouse (Europe, Brazil) (En)"},
["0ca95637"] = {name = "Laser Ghost (Europe)"},
["6350e649"] = {name = "Legend of Illusion Starring Mickey Mouse (Brazil) (En)"},
["2c61ed88"] = {name = "Lemmings (Europe) (Beta)"},
["f369b2d8"] = {name = "Lemmings (Europe, Brazil) (En)"},
["cf5aecca"] = {name = "Lemmings 2 - The Tribes (Europe) (Proto) (1995-09-04)"},
["eb71247b"] = {name = "Lethal Weapon 3 Music (Unknown) (Proto) (1992-11-30) (Sound Data)"},
["cb09f355"] = {name = "Line of Fire (Europe, Brazil) (En)"},
["c352c7eb"] = {name = "Lion King, The (Europe, Brazil) (En)"},
["aa7d6f45"] = {name = "Lord of Sword (Japan)"},
["7eaed675"] = {name = "Lord of Sword (Taiwan) (Ja) (Unl)"},
["e8511b08"] = {name = "Lord of the Sword (USA, Europe, Brazil) (En)"},
["323f357f"] = {name = "Loretta no Shouzou - Sherlock Holmes (Japan)"},
["a1710f13"] = {name = "Lucky Dime Caper Starring Donald Duck, The (Europe, Brazil) (En)"},
["7f6d0df6"] = {name = "Lucky Dime Caper Starring Donald Duck, The (Europe, Brazil) (En) (Beta)"},
["996b2a07"] = {name = "Mahjong Sengoku Jidai (Japan) (Beta)"},
["bcfbfc67"] = {name = "Mahjong Sengoku Jidai (Japan, Hong Kong) (Ja)"},
["ca860451"] = {name = "Makai Retsuden (Japan)"},
["bf0411ad"] = {name = "Maou Golvellius (Japan)"},
["21a21352"] = {name = "Maou Golvellius (Japan) (Beta)"},
["bf6f3e5f"] = {name = "Marble Madness (Europe)"},
["e8ea842c"] = {name = "Marksman Shooting & Trap Shooting (USA, Brazil) (En)"},
["e8215c2e"] = {name = "Marksman Shooting & Trap Shooting & Safari Hunt (Europe)"},
["96fb4d4b"] = {name = "Master of Darkness (Europe, Brazil) (En)"},
["93141463"] = {name = "Masters of Combat (Europe, Brazil) (En)"},
["31b8040b"] = {name = "Maze Hunter 3-D (USA, Europe, Brazil) (En)"},
["871562b0"] = {name = "Maze Walker (Japan) (En)"},
["f8ce3cc3"] = {name = "Maze Walker (Japan) (En) (Sega 3D Classics)"},
["29bc7fad"] = {name = "Megumi Rescue (Japan)"},
["e2f0fc48"] = {name = "Memoria Master (Brazil) (Mega Drive 4)"},
["d7416b83"] = {name = "Mercs (Europe, Brazil) (En)"},
["56cc906b"] = {name = "Michael Jackson's Moonwalker (USA, Europe, Brazil) (En)"},
["54123936"] = {name = "Michael Jackson's Moonwalker (USA, Europe, Brazil) (En) (Beta)"},
["2b86bcd7"] = {name = "Mickey's Ultimate Challenge (Brazil) (En)"},
["a577ce46"] = {name = "Micro Machines (Europe)"},
["41cc2ade"] = {name = "Micro Xevious, The (Korea) (Unl)"},
["52d73c83"] = {name = "Mina Terrestre (Brazil) (Mega Drive 4)"},
["67f67844"] = {name = "Minerador (Brazil) (Mega Drive 4)"},
["301a59aa"] = {name = "Miracle Warriors - Seal of The Dark Lord (USA, Europe, Brazil) (En) (Beta) (1988-02-25)"},
["0e333b6e"] = {name = "Miracle Warriors - Seal of The Dark Lord (USA, Europe, Brazil) (En)"},
["fbe5cfbb"] = {name = "Missile Defense 3-D (USA, Europe, Brazil) (En)"},
["43def05d"] = {name = "Missile Defense 3-D (USA, Europe, Brazil) (En) (Sample)"},
["01d67c0b"] = {name = "Monica no Castelo do Dragao (Brazil)"},
["7e9d87fc"] = {name = "Monopoly (USA, Europe) (Beta 1)"},
["69538469"] = {name = "Monopoly (USA, Europe)"},
["026d94a4"] = {name = "Monopoly (Europe) (Rev A)"},
["e0d1049b"] = {name = "Monopoly (USA, Europe) (Beta 2)"},
["575d0fcf"] = {name = "Montezuma's Revenge - Featuring PANAMA JOE (USA) (Beta)"},
["82fda895"] = {name = "Montezuma's Revenge - Featuring PANAMA JOE (USA)"},
["b49aa6fc"] = {name = "Mopiranger (Korea) (En) (Unl)"},
["302dc686"] = {name = "Mortal Kombat (Europe, Brazil) (En)"},
["395ae757"] = {name = "Mortal Kombat 3 (Brazil) (En)"},
["2663bf18"] = {name = "Mortal Kombat II (Europe, Brazil) (En)"},
["3cd816c6"] = {name = "Ms. Pac-Man (Europe, Brazil) (En)"},
["ff5091e0"] = {name = "MSX Soccer (Korea) (Unl)"},
["62f0c23d"] = {name = "My Hero (USA, Europe, Brazil) (En)"},
["332a847d"] = {name = "NBA Jam (Europe) (Proto)"},
["5b5f9106"] = {name = "Nekkyuu Koushien (Japan)"},
["e316c06d"] = {name = "Nemesis (Korea) (Unl)"},
["0a77fa5e"] = {name = "Nemesis 2 (Korea) (En) (Unl)"},
["dbbf4dd1"] = {name = "New Boggle Boggle 2 (Korea) (En) (Unl)"},
["c660ff34"] = {name = "NewZealand Story, The (Europe)"},
["320313ec"] = {name = "Ninja (Japan)"},
["1b1d8cc2"] = {name = "Ninja Gaiden (Europe, Brazil) (En)"},
["761e9396"] = {name = "Ninja Gaiden (Europe, Brazil) (En) (Beta)"},
["66a15bd9"] = {name = "Ninja, The (USA, Europe, Brazil) (En)"},
["2cd62dca"] = {name = "Ninja, The (Taiwan) (Unl)"},
["b6207f0d"] = {name = "Northen Ken (Taiwan) (Ja) (Unl)"},
["d1a7b1aa"] = {name = "Olympic Gold (Brazil) (En,Fr,De,Es,It,Nl,Pt,Sv)"},
["6a5a1e39"] = {name = "Olympic Gold (Europe) (En,Fr,De,Es,It,Nl,Pt,Sv)"},
["bea27d5c"] = {name = "Opa Opa (Japan)"},
["205caae8"] = {name = "Operation Wolf (Europe, Brazil) (En)"},
["82ef2a7d"] = {name = "Ottifants, The (Europe, Brazil) (En,Fr,De,Es,It)"},
["5589d8d2"] = {name = "OutRun (World)"},
["d6f43dda"] = {name = "OutRun 3-D (Europe, Brazil) (En)"},
["4e684ec0"] = {name = "OutRun 3-D (Europe, Brazil) (En) (Beta)"},
["b883c836"] = {name = "OutRun 3-D (Japan) (En) (Sega 3D Fukkoku Akaibusu)"},
["3932adbc"] = {name = "OutRun Europa (Europe, Brazil) (En)"},
["be57a9a5"] = {name = "Pac-Mania (Europe)"},
["ca5424e6"] = {name = "Palhacos (Brazil) (Mega Drive 4)"},
["354bee78"] = {name = "Paper Boy (Taiwan) (En) (Unl)"},
["327a0b4c"] = {name = "Paperboy (USA, Brazil) (En)"},
["294e0759"] = {name = "Paperboy (Europe)"},
["e030e66c"] = {name = "Parlour Games (USA, Europe)"},
["9aefe664"] = {name = "Pat Riley Basketball (USA) (Proto)"},
["445525e2"] = {name = "Penguin Adventure (Korea) (En) (Unl)"},
["f97e9875"] = {name = "Penguin Land (USA, Europe)"},
["95b9ea95"] = {name = "PGA Tour Golf (Europe)"},
["00bef1d7"] = {name = "Phantasy Star (USA, Europe) (Rev A)"},
["75971bef"] = {name = "Phantasy Star (Brazil)"},
["e4a65e79"] = {name = "Phantasy Star (USA, Europe)"},
["6605d36a"] = {name = "Phantasy Star (Japan)"},
["747e83b5"] = {name = "Phantasy Star (Korea) (Unl)"},
["07301f83"] = {name = "Phantasy Star (Japan) (Virtual Console)"},
["a1e090b9"] = {name = "Phantasy Star (World) (Sega Ages)"},
["df96f194"] = {name = "Phantasy Star (World) (Ja) (Sega Ages)"},
["c0ac6956"] = {name = "Pigu-Wang 7 Hap - Jaemiiss-neun Game Mo-eumjip (Korea) (Unl)"},
["aa4d4b5a"] = {name = "Pit-Fighter (Brazil) (En)"},
["b840a446"] = {name = "Pit-Fighter (Europe)"},
["ca082218"] = {name = "Pooyan (Korea) (En) (Unl)"},
["c7a1fdef"] = {name = "Populous (Europe, Brazil) (En)"},
["abd48ad2"] = {name = "Poseidon Wars 3-D (USA, Europe, Brazil) (En)"},
["6d309ac5"] = {name = "Power Boggle Boggle (Korea) (En) (Unl)"},
["4077efd9"] = {name = "Power Strike (USA, Europe, Brazil) (En)"},
["a109a6fe"] = {name = "Power Strike II (Europe, Brazil) (En)"},
["7778e256"] = {name = "Ppang Gongjang (Korea) (En) (Unl)"},
["2b54c82b"] = {name = "Predator 2 (Brazil) (En)"},
["0047b615"] = {name = "Predator 2 (Europe)"},
["7704287d"] = {name = "Prince of Persia (Europe, Brazil) (En)"},
["cafd2d83"] = {name = "Prince of Persia (Taiwan) (En) (Unl)"},
["fbde42d3"] = {name = "Pro Wrestling (USA, Europe, Brazil) (En)"},
["da9be8f0"] = {name = "Pro Yakyuu, The - Pennant Race (Japan)"},
["30af0233"] = {name = "Promocao Especial M. System III Compact (Brazil) (Sample)"},
["5c0b1f0f"] = {name = "Psychic World (Europe, Brazil) (En)"},
["97993479"] = {name = "Psycho Fox (USA, Europe, Brazil) (En)"},
["4bf0e1cc"] = {name = "Psycho Fox (USA, Europe, Brazil) (En) (Beta)"},
["357d4f78"] = {name = "Putt & Putter (Europe, Brazil) (En)"},
["8167ccc4"] = {name = "Putt & Putter (Europe, Brazil) (En) (Beta)"},
["76e8265f"] = {name = "Puzzle Game (Korea) (En) (Unl)"},
["e0f34fa6"] = {name = "Quartet (USA, Europe)"},
["cacdf759"] = {name = "Quartet (Taiwan) (En) (Unl)"},
["f42e145c"] = {name = "Quest for the Shaven Yak Starring Ren Hoek & Stimpy (Brazil) (En)"},
["0d0840d5"] = {name = "R-Type (World) (Beta)"},
["bb54b6b0"] = {name = "R-Type (World)"},
["e532716f"] = {name = "R-Type (Taiwan) (En) (Unl)"},
["767f11b8"] = {name = "R.C. Grand Prix (USA, Europe, Brazil) (En) (Beta)"},
["54316fea"] = {name = "R.C. Grand Prix (USA, Europe, Brazil) (En)"},
["00ec173a"] = {name = "Rainbow Islands (Brazil) (En)"},
["c172a22c"] = {name = "Rainbow Islands (Europe)"},
["bbda65f0"] = {name = "Rambo - First Blood Part II (USA)"},
["da5a7013"] = {name = "Rambo III (USA, Europe, Brazil) (En)"},
["42fc47ee"] = {name = "Rampage (USA, Europe, Brazil) (En)"},
["0e0d6c7a"] = {name = "Rampage (USA, Europe, Brazil) (En) (Beta)"},
["426e5c8a"] = {name = "Rampart (Europe)"},
["c547eb1b"] = {name = "Rastan (USA, Europe, Brazil) (En)"},
["f063bfc8"] = {name = "Rastan (USA, Europe, Brazil) (En) (Beta)"},
["6d94bb0e"] = {name = "Reggie Jackson Baseball (USA)"},
["3be7f641"] = {name = "Renegade (Europe, Brazil) (En)"},
["79ac8e7f"] = {name = "Rescue Mission (USA, Europe, Brazil) (En)"},
["8034bd27"] = {name = "Road Fighter (Korea) (En) (Unl)"},
["b876fc74"] = {name = "Road Rash (Europe, Brazil) (En)"},
["9f951756"] = {name = "RoboCop 3 (Europe, Brazil) (En)"},
["8212b754"] = {name = "RoboCop versus The Terminator (Europe, Brazil) (En)"},
["1bcc7be3"] = {name = "Rocky (World)"},
["1fdae719"] = {name = "Running Battle (Europe, Brazil) (En)"},
["66388128"] = {name = "Sagaia (Europe, Brazil) (En)"},
["643b6b76"] = {name = "Sagak-ui Bimil (Korea) (En) (Unl)"},
["97d03541"] = {name = "Samgukji 3 (Korea) (Unl)"},
["0e7a5f9f"] = {name = "Sapo Xule - O Mestre do Kung Fu (Brazil)"},
["7ab2946a"] = {name = "Sapo Xule - S.O.S. Lagoa Poluida (Brazil, Portugal) (Pt)"},
["9a608327"] = {name = "Sapo Xule vs. Os Invasores do Brejo (Brazil)"},
["16249e19"] = {name = "Satellite 7 (Japan)"},
["7982ae67"] = {name = "Schtroumpfs Autour du Monde, Les (Europe) (En,Fr,De,Es) (Beta) (1996-08-12)"},
["97e5bb7d"] = {name = "Schtroumpfs Autour du Monde, Les (Europe) (En,Fr,De,Es)"},
["9a8b28ec"] = {name = "Scramble Spirits (Europe, Brazil) (En)"},
["7d59283b"] = {name = "Scramble Spirits (Taiwan) (En) (Unl)"},
["b45d4700"] = {name = "Scramble Spirits (Europe, Brazil) (En) (Beta)"},
["1de2c2d0"] = {name = "SDI (Japan)"},
["00529114"] = {name = "Secret Command (Europe)"},
["a8061aef"] = {name = "Sega Chess (Europe, Brazil) (En)"},
["276aa542"] = {name = "Sega Graphic Board (USA) (v2.0) (Proto)"},
["296879dd"] = {name = "Sega World Tournament Golf (Europe, Brazil) (En)"},
["f0ba2bc6"] = {name = "Seishun Scandal (Japan)"},
["c92d2101"] = {name = "Senha (Brazil) (Mega Drive 4)"},
["f8176918"] = {name = "Sensible Soccer (Europe)"},
["ab67c6bd"] = {name = "Shadow Dancer (Taiwan) (En) (Unl)"},
["3793c01a"] = {name = "Shadow Dancer - The Secret of Shinobi (Europe, Brazil) (En)"},
["1575581d"] = {name = "Shadow of the Beast (Europe, Brazil) (En)"},
["ac2ea669"] = {name = "Shadow of the Beast (Taiwan) (En) (Unl)"},
["d5d25156"] = {name = "Shanghai (USA, Europe) (Beta)"},
["aab67ec3"] = {name = "Shanghai (USA, Europe)"},
["89efcc22"] = {name = "Shangwei Mingling (Taiwan) (En) (Unl)"},
["0c6fac4e"] = {name = "Shinobi (USA, Europe, Brazil) (En) (Rev 1)"},
["e1fff1bb"] = {name = "Shinobi (Japan, Brazil) (Ja)"},
["4b051022"] = {name = "Shooting Gallery (USA, Europe, Brazil) (En)"},
["d1cc08ee"] = {name = "Simpsons, The - Bart vs. The Space Mutants (Europe, Brazil) (En)"},
["f6b2370a"] = {name = "Simpsons, The - Bart vs. The World (Europe, Brazil) (En)"},
["abdf3923"] = {name = "Sitio do Picapau Amarelo (Brazil)"},
["77ba2667"] = {name = "Sky Fighter (Korea) (En) (Unl)"},
["5b8e65e4"] = {name = "Sky Jaguar (Korea) (Unl)"},
["e3f260ca"] = {name = "Sky Jaguar (Korea) (Clover) (Unl)"},
["fbb0a92a"] = {name = "Slap Shoot (USA) (Beta)"},
["702c3e98"] = {name = "Slap Shot (USA, Europe, Brazil) (En)"},
["d33b296a"] = {name = "Slap Shot (Europe) (Sample)"},
["c93bd0e9"] = {name = "Slap Shot (Europe)"},
["3e63768a"] = {name = "Smurfs, The (Europe, Brazil) (En,Fr,De,Es)"},
["11645549"] = {name = "Solomon no Kagi - Oujo Rihita no Namida (Japan)"},
["92dc4cd6"] = {name = "Solomon no Kagi - Oujo Rihita no Namida (Japan) (Beta)"},
["96b3f29e"] = {name = "Sonic Blast (Brazil) (En)"},
["aedf3bdf"] = {name = "Sonic Chaos (Europe, Brazil) (En)"},
["d3ad67fa"] = {name = "Sonic Chaos (Europe, Brazil) (En) (Beta) (1993-06-30)"},
["765234d8"] = {name = "Sonic Chaos (Europe, Brazil) (En) (Beta) (1993-07-13)"},
["11c1bc8a"] = {name = "Sonic Spinball (Europe, Brazil) (En)"},
["b519e833"] = {name = "Sonic The Hedgehog (USA, Europe, Brazil) (En)"},
["d6f2bfca"] = {name = "Sonic The Hedgehog 2 (Europe, Brazil) (En) (Rev 1)"},
["5b3b922c"] = {name = "Sonic The Hedgehog 2 (Europe, Brazil) (En)"},
["d9096263"] = {name = "Sonic's Edusoft (Unknown) (Proto)"},
["a908cff5"] = {name = "Space Gun (Europe)"},
["beddf80e"] = {name = "Space Harrier (Japan, USA) (En)"},
["ca1d3752"] = {name = "Space Harrier (Europe)"},
["6bd5c2bf"] = {name = "Space Harrier 3-D (USA, Europe, Brazil) (En)"},
["156948f9"] = {name = "Space Harrier 3D (Japan)"},
["1b7d2a20"] = {name = "Special Criminal Investigation (Europe) (Beta)"},
["fa8e4ca0"] = {name = "Special Criminal Investigation (Europe)"},
["5ccc1a65"] = {name = "Speedball (Europe) (Rev 1)"},
["a57cad18"] = {name = "Speedball (Europe)"},
["0c7366a0"] = {name = "Speedball 2 (Europe)"},
["4752cae7"] = {name = "SpellCaster (USA, Europe, Brazil) (En)"},
["908ff25c"] = {name = "Spider-Man (USA, Europe, Brazil) (En)"},
["ebe45388"] = {name = "Spider-Man - Return of the Sinister Six (Europe, Brazil) (En)"},
["e42e4998"] = {name = "Sports Pad Football (USA)"},
["41c948bf"] = {name = "Sports Pad Soccer (Japan)"},
["d41b9a08"] = {name = "Spy vs Spy (Japan)"},
["78d7faab"] = {name = "Spy vs Spy (USA, Europe, Brazil) (En)"},
["689f58a2"] = {name = "Spy vs Spy (Taiwan) (Unl)"},
["d4b8f66d"] = {name = "Star Wars (Europe, Brazil) (En)"},
["0f8287ec"] = {name = "Street Fighter II' (Brazil) (En)"},
["83f0eede"] = {name = "Street Master (Korea) (Unl)"},
["4ab3790f"] = {name = "Streets of Rage (Europe, Brazil) (En)"},
["04e9c089"] = {name = "Streets of Rage II (Europe, Brazil) (En)"},
["b990269a"] = {name = "Strider (USA, Europe, Brazil) (En) (Demo)"},
["9802ed31"] = {name = "Strider (USA, Europe, Brazil) (En)"},
["b8f0915a"] = {name = "Strider II (Europe, Brazil) (En)"},
["63a7f906"] = {name = "Strider, The (Taiwan) (En) (Unl)"},
["d8f2f1b9"] = {name = "Submarine Attack (Europe, Brazil) (En)"},
["d282ef71"] = {name = "Submarine Attack (Taiwan) (En) (Unl)"},
["814c08d1"] = {name = "Sudoku (Brazil) (Mega Drive 4)"},
["01686d67"] = {name = "Suho Jeonsa (Korea) (Unl)"},
["b13df647"] = {name = "Sukeban Deka II - Shoujo Tekkamen Densetsu (Japan)"},
["8da5c93f"] = {name = "Summer Games (Europe, Brazil) (En)"},
["80eb1fff"] = {name = "Summer Games (Europe, Brazil) (En) (Beta 2)"},
["4f530cb2"] = {name = "Summer Games (Europe, Brazil) (En) (Beta 1)"},
["c9dd4e5f"] = {name = "Super Arkanoid (Korea) (Unl)"},
["0dbf3b4a"] = {name = "Super Basketball (USA) (Demo)"},
["a66d26cf"] = {name = "Super Bioman I (Korea) (Unl)"},
["b995b4f0"] = {name = "Super Boy 4 (Korea) (Unl)"},
["bf5a994a"] = {name = "Super Boy I (Korea) (En) (Unl)"},
["67c2f0ff"] = {name = "Super Boy II (Korea) (En) (Unl)"},
["9195c34c"] = {name = "Super Boy III (Korea) (En) (Unl)"},
["22c09cfd"] = {name = "Super Bubble Bobble (Korea) (En) (Unl)"},
["6ce7f694"] = {name = "Super Columns & Tetris (Korea) (Unl)"},
["551e6f51"] = {name = "Super Futebol II (Brazil)"},
["1b8956d1"] = {name = "Super Game 150 (Korea) (Unl)"},
["4e202aa2"] = {name = "Super Game 180 (Korea) (Unl)"},
["edb13847"] = {name = "Super Game 45 (Korea) (Unl)"},
["a841c0b7"] = {name = "Super Game 52 Hap (Korea) (Unl)"},
["e6ad4d4b"] = {name = "Super Game World 30 Hap (Korea) (v1.1) (Unl)"},
["0cde0938"] = {name = "Super Game World 30 Hap (Korea) (Unl)"},
["c29bb8cd"] = {name = "Super Game World 75 Hap (Korea) (Unl)"},
["7f7b568d"] = {name = "Super Golf (Europe) (Beta)"},
["406aa0c2"] = {name = "Super Kick Off (Europe, Brazil) (En,Fr,De,Es,It,Nl,Pt,Sv)"},
["3ef12baa"] = {name = "Super Monaco GP (USA)"},
["a1d6d963"] = {name = "Super Monaco GP (Europe, Brazil) (En) (Beta)"},
["dd7adbcc"] = {name = "Super Monaco GP (USA) (Beta 1)"},
["55bf81a0"] = {name = "Super Monaco GP (Europe, Brazil) (En)"},
["3753cc95"] = {name = "Super Monaco GP (USA) (Beta 2)"},
["eb7790de"] = {name = "Super Multi Game - Super 125 in 1 (Korea) (Unl)"},
["660bf6ec"] = {name = "Super Multi Game - Super 75 in 1 (Korea) (Unl)"},
["54f68c2a"] = {name = "Super Off Road (Europe)"},
["ce8d6846"] = {name = "Super Off Road (Europe) (Beta)"},
["53d742db"] = {name = "Super Penguin (Korea) (Unl)"},
["7e0ef8cb"] = {name = "Super Racing (Japan)"},
["e0b1aff8"] = {name = "Super Smash T.V. (Europe)"},
["1d6244ee"] = {name = "Super Space Invaders (Europe)"},
["914514e3"] = {name = "Super Tennis (USA, Europe)"},
["bd1cc7df"] = {name = "Super Tetris (Korea) (Unl)"},
["b1da6a30"] = {name = "Super Wonder Boy - Monster World (Japan)"},
["6f9ac98f"] = {name = "Superman - The Man of Steel (Europe, Brazil) (En)"},
["93ca8152"] = {name = "T2 - The Arcade Game (Europe)"},
["85cfc9c9"] = {name = "Taito Chase H.Q. (Europe)"},
["1cdcf415"] = {name = "Taito Chase H.Q. (Europe) (Beta)"},
["d72eaea6"] = {name = "Tangram (Brazil) (Mega Drive 4)"},
["42d911f3"] = {name = "Tank Battalion (Korea) (Unl)"},
["11ce074c"] = {name = "Taz in Escape from Mars (Brazil) (En)"},
["1b312e04"] = {name = "Taz-Mania (Europe, Brazil) (En) (Beta)"},
["7cc3e837"] = {name = "Taz-Mania (Europe, Brazil) (En)"},
["96e75f48"] = {name = "Tecmo World Cup '92 (Europe) (Beta)"},
["5a1c3dde"] = {name = "Tecmo World Cup '93 (Europe)"},
["2728faa3"] = {name = "Teddy Boy (USA, Europe, Brazil) (En)"},
["d7508041"] = {name = "Teddy Boy Blues (Japan) (Proto) (Ep-MyCard)"},
["316727dd"] = {name = "Teddy Boy Blues (Japan)"},
["1a390b93"] = {name = "Tennis Ace (Europe, Brazil) (En)"},
["8132ab2c"] = {name = "Tensai Bakabon (Japan)"},
["ac56104f"] = {name = "Terminator 2 - Judgment Day (Europe)"},
["e3d5ce9a"] = {name = "Terminator, The (Brazil) (En)"},
["edc5c012"] = {name = "Terminator, The (Europe)"},
["8640e7e8"] = {name = "Three Dragon Story, The (Korea) (Unl)"},
["ae920e4b"] = {name = "Thunder Blade (USA, Europe, Brazil) (En)"},
["c0ce19b1"] = {name = "Thunder Blade (Japan)"},
["98cf1254"] = {name = "Thunder Blade (Taiwan) (En) (Unl)"},
["bab9533b"] = {name = "Thunder Blade (USA, Europe, Brazil) (En) (Beta)"},
["51bd14be"] = {name = "Time Soldiers (USA, Europe, Brazil) (En)"},
["0c2fc2de"] = {name = "Tom & Jerry (Europe, Brazil) (En) (Beta)"},
["bf7b7285"] = {name = "Tom and Jerry - The Movie (Europe, Brazil) (En)"},
["4f8d75ec"] = {name = "Toto World 3 (Korea) (Unl)"},
["4bc42857"] = {name = "TransBot (USA, Europe, Brazil) (En)"},
["58b99750"] = {name = "TransBot (USA, Europe, Brazil) (En) (Beta)"},
["e5374022"] = {name = "Trivial Pursuit - Genus Edition (Europe) (En,Fr,De,Es)"},
["178801d2"] = {name = "Ttoriui Moheom (Korea) (En) (Unl)"},
["22cca9bb"] = {name = "Turma da Monica em O Resgate (Brazil)"},
["b52d60c8"] = {name = "Ultima IV - Quest of the Avatar (Europe, Brazil) (En)"},
["de9f8517"] = {name = "Ultima IV - Quest of the Avatar (Europe, Brazil) (En) (Beta)"},
["15668ca4"] = {name = "Ultimate Soccer (Europe, Brazil) (En,Fr,De,Es,It)"},
["20f40cae"] = {name = "Vampire (Europe) (Beta)"},
["dfb0b161"] = {name = "Vigilante (USA, Europe, Brazil) (En)"},
["57f1545b"] = {name = "Virtua Fighter Animation (Brazil) (En)"},
["3d55759b"] = {name = "Walter Payton Football (USA)"},
["5359762d"] = {name = "Wanted (USA, Europe, Brazil) (En)"},
["428b1e7c"] = {name = "Where in the World is Carmen Sandiego (USA)"},
["88aa8ca6"] = {name = "Where in the World is Carmen Sandiego (Brazil) (En)"},
["912d92af"] = {name = "Wimbledon (Europe)"},
["b14b6195"] = {name = "Wimbledon (Brazil) (En)"},
["7f3afe58"] = {name = "Wimbledon II (Europe, Brazil) (En)"},
["a20290b6"] = {name = "Winter Olympics (Europe) (En,Fr,De,Es,It,Pt,Sv,No)"},
["2fec2b4a"] = {name = "Winter Olympics (Brazil) (En,Fr,De,Es,It,Pt,Sv,No)"},
["1f8efa1d"] = {name = "Wolfchild (Europe, Brazil) (En)"},
["73705c02"] = {name = "Wonder Boy (USA, Europe, Brazil) (En) (Rev 1)"},
["e2fcb6f3"] = {name = "Wonder Boy (Japan, Europe) (En)"},
["679e1676"] = {name = "Wonder Boy III - The Dragon's Trap (USA, Europe)"},
["8312c429"] = {name = "Wonder Boy in Monster Land (USA, Europe) (Beta)"},
["8cbef0c1"] = {name = "Wonder Boy in Monster Land (USA, Europe)"},
["81bff9bb"] = {name = "Wonder Boy in Monster World (Europe) (Beta)"},
["7d7ce80b"] = {name = "Wonder Boy in Monster World (Europe)"},
["a05258f5"] = {name = "Wonsiin (Korea) (Unl)"},
["315917d4"] = {name = "Woody Pop - Shinjinrui no Block Kuzushi (Japan)"},
["c9a449b7"] = {name = "World Class Leaderboard (Europe, Brazil) (En)"},
["a0cf8b15"] = {name = "World Cup Italia '90 (USA) (Demo)"},
["6e1ad6fd"] = {name = "World Cup Italia '90 (Europe, Brazil) (En)"},
["a6bf8f9e"] = {name = "World Cup USA 94 (Europe, Brazil) (En,Fr,De,Es,It,Nl,Pt,Sv)"},
["a2a60bc8"] = {name = "World Games (Europe, Brazil) (En)"},
["914d3fc4"] = {name = "World Games (Europe, Brazil) (En) (Beta)"},
["b5a9f824"] = {name = "World Grand Prix (USA, Brazil) (En) (Beta)"},
["4aaad0d6"] = {name = "World Grand Prix (Europe)"},
["7b369892"] = {name = "World Grand Prix (USA, Brazil) (En)"},
["72112b75"] = {name = "World Soccer (World)"},
["2db21448"] = {name = "WWF Wrestlemania - Steel Cage Challenge (Europe, Brazil) (En)"},
["3e1387f6"] = {name = "X-Men - Mojo World (Brazil) (En)"},
["5c205ee1"] = {name = "Xenon 2 - Megablast (Europe)"},
["ec726c0d"] = {name = "Xenon 2 - Megablast (Europe) (Rev 1)"},
["565c799f"] = {name = "Xyzolog (Korea) (En) (Unl)"},
["32759751"] = {name = "Ys (Japan)"},
["e8b82066"] = {name = "Ys - The Vanished Omens (USA, Europe) (Ja) (Demo)"},
["b33e2827"] = {name = "Ys - The Vanished Omens (USA, Europe, Brazil) (En)"},
["1203afc9"] = {name = "Yuyryeong-ui Jip (Korea) (Unl)"},
["bba74147"] = {name = "Zaxxon 3-D (World) (Beta)"},
["a3ef13cb"] = {name = "Zaxxon 3-D (World)"},
["e6c9c046"] = {name = "Zemina Best 25 (Korea) (Unl)"},
["d8169fe2"] = {name = "Zemina Best 39 (Korea) (Unl)"},
["3c339d9e"] = {name = "Zemina Best 88 (Korea) (Unl)"},
["7cd51467"] = {name = "Zemina Rompack - Q-Bert + Sports 3 + Gulkave + Pooyan (Korea) (Unl)"},
["60c19645"] = {name = "Zillion (Japan, Europe) (En,Ja)"},
["5718762c"] = {name = "Zillion (USA, Europe) (Rev 1)"},
["7ba54510"] = {name = "Zillion (Europe, Brazil) (En) (Rev 2)"},
["2f2e3bc9"] = {name = "Zillion II - The Tri Formation (World)"},
["5b1cf392"] = {name = "Zillion II - The Tri Formation (World) (Beta)"},
["9d9d0a5f"] = {name = "Zool - Ninja of the 'Nth' Dimension (Europe)"},
}